import { BsLightningChargeFill } from "react-icons/bs";
import { FaArrowDown } from "react-icons/fa";
import { IoMdLock } from "react-icons/io";
import { MdOutlineVerifiedUser } from "react-icons/md";
import { FaRobot } from "react-icons/fa6";
import { FaUserAstronaut } from "react-icons/fa6";

import Icons from "../components/global/icons";
export const config = {
  site_name: "Live Trading",
  site_title: "Live trading - Your Trusted Trading Platform",
  site_description:
    "Live trading is a reliable and secure platform for trading financial instruments. Join us to experience a seamless and efficient trading environment.",
  logo: "/logo.png",
  site_slogan: "Trading with ease",
  login_url: "/traderoom/#/login",
  email: "support@livetrader.com",
  signup_url: "/traderoom/#/register",
  forgot_password: "/forgot_password",
};

export const Major = [
  {
    SYMBOL: "AUDUSD",
    DESCRIPTION: "Australian Dollar vs United States Dollar",
    MIN: "0",
    AVG: "0.03",
    MIN2: "0.8",
    AVG2: "0.83",
  },
  {
    SYMBOL: "EURUSD",
    DESCRIPTION: "Euro vs United States Dollar",
    MIN: "0",
    AVG: "0.02",
    MIN2: "o.8",
    AVG2: "0.82",
  },
  {
    SYMBOL: "GBPUSD",
    DESCRIPTION: "British Pound vs United States Dollar",
    MIN: "0",
    AVG: "0.23",
    MIN2: "0.8",
    AVG2: "1.03",
  },
  {
    SYMBOL: "USDCAD",
    DESCRIPTION: "United States Dollar vs Canadian Dollar",
    MIN: "0",
    AVG: "0.25",
    MIN2: "0.8",
    AVG2: "1.05",
  },
  {
    SYMBOL: "USDCHF",
    DESCRIPTION: "United States Dollar vs Swiss Franc",
    MIN: "0",
    AVG: "0.19",
    MIN2: "0.8",
    AVG2: "0.99",
  },
  {
    SYMBOL: "USDJPY",
    DESCRIPTION: "United States Dollar vs Japanese Yen",
    MIN: "0",
    AVG: "0.14",
    MIN2: "0.8",
    AVG2: "0.94",
  },
];

export const AUD = [
  {
    title: "Credit and Debit Cards",
    img: "/funding/mastercar.webp",
    img2: "/funding/visa.webp",
    Currencies: {
      currency: [
        { Currency: "AUD" },
        { Currency: "USD" },
        { Currency: "JPY" },
        { Currency: "EUR" },
        { Currency: "NZD" },
        { Currency: "SGD" },
        { Currency: "GPB" },
        { Currency: "CAD" },
      ],
    },
    time: "INSTANT",
  },
  {
    title: "PayPal",
    img: "/funding/paypal.webp",
    Currencies: {
      currency: [
        { Currency: "AUD" },
        { Currency: "USD" },
        { Currency: "JPY" },
        { Currency: "EUR" },
        { Currency: "NZD" },
        { Currency: "SGD" },
        { Currency: "GPB" },
        { Currency: "CAD" },
        { Currency: "HKD" },
        { Currency: "CHF" },
      ],
    },
    time: "INSTANT",
  },
  {
    title: "Neteller",
    img: "/funding/neteller.webp",
    Currencies: {
      currency: [
        { Currency: "AUD" },
        { Currency: "USD" },
        { Currency: "JPY" },
        { Currency: "EUR" },
        { Currency: "SGD" },
        { Currency: "GPB" },
        { Currency: "CAD" },
      ],
    },
    time: "INSTANT",
  },
  {
    title: "Neteller VIP",
    img: "/funding/neteller.webp",
    Currencies: {
      currency: [
        { Currency: "AUD" },
        { Currency: "JPY" },
        { Currency: "EUR" },
        { Currency: "SGD" },
        { Currency: "GPB" },
        { Currency: "CAD" },
      ],
    },
    time: "INSTANT",
  },
  {
    title: "Wire Transfer",
    img: "/funding/paypal.webp",
    Currencies: {
      currency: [
        { Currency: "AUD" },
        { Currency: "USD" },
        { Currency: "JPY" },
        { Currency: "EUR" },
        { Currency: "NZD" },
        { Currency: "SGD" },
        { Currency: "GPB" },
        { Currency: "CAD" },
        { Currency: "CHF" },
      ],
    },
    time: "INSTANT",
  },
  {
    title: "Skrill",
    img: "/funding/skrill.webp",
    Currencies: {
      currency: [
        { Currency: "AUD" },
        { Currency: "JPY" },
        { Currency: "EUR" },
        { Currency: "SGD" },
        { Currency: "GBP" },
      ],
    },
    time: "INSTANT",
  },
  {
    title: "Bpay",
    img: "/funding/bpay.webp",
    Currencies: {
      currency: [{ Currency: "AUD" }],
    },
    time: "INSTANT",
  },
  {
    title: "Broker to Broker",
    img: "/funding/broker.webp",
    Currencies: {
      currency: [
        { Currency: "AUD" },
        { Currency: "JPY" },
        { Currency: "EUR" },
        { Currency: "SGD" },
        { Currency: "GBP" },
        { Currency: "USD" },
        { Currency: "NZD" },
        { Currency: "CAD" },
        { Currency: "CHF" },
        { Currency: "HKD" },
      ],
    },
    time: "INSTANT",
  },
  {
    title: "Bpay",
    img: "/funding/bpay.webp",
    Currencies: {
      currency: [{ Currency: "AUD" }],
    },
    time: "INSTANT",
  },
];

export const CAD = [
  {
    title: "Credit and Debit Cards",
    img: "/funding/mastercar.webp",
    img2: "/funding/visa.webp",
    Currencies: {
      currency: [
        { Currency: "AUD" },
        { Currency: "USD" },
        { Currency: "JPY" },
        { Currency: "EUR" },
        { Currency: "NZD" },
        { Currency: "SGD" },
        { Currency: "GPB" },
        { Currency: "CAD" },
      ],
    },
    time: "INSTANT",
  },
];

export const Digitalcurrency = [
  {
    Img: "/digitalcurrency/btc-color.webp",
    Title: "Bitcoin CFD",
    Details:
      "The first and largest cryptocurrency, Bitcoin paved the ways for hundreds of similar currencies and boasts a market cap of over $100 billion.",
  },
  {
    Img: "/digitalcurrency/ethereum-color.webp",
    Title: "Ethereum CFD",
    Details:
      "The world's second-largest cryptocurrency, it is labelled by many as 'the next Bitcoin'. Ethereum has received international recognition and support from giant organisations such as Microsoft, JP Morgan, and Intel",
  },
  {
    Img: "/digitalcurrency/dash-color.webp",
    Title: "Dash CFD",
    Details:
      "Dash's focus is on instant transactions and owner privacy. Dash has an infrastructure that enables much faster transactions than other cryptocurrencies and therefore displays higher liquidity than many of its counterparts.",
  },
  {
    Img: "/digitalcurrency/lite-color.webp",
    Title: "Litecoin CFD",
    Details:
      "Designed by a former Google engineer to improve upon Bitcoin's technology, Litecoin offers quicker processing times and a larger number of tokens. It is also the first cryptocurrency to implement SegWit, a method of speeding up transaction times without compromising the underlying blockchain technology.",
  },
  {
    Img: "/digitalcurrency/btc-cash-color.webp",
    Title: "Litecoin CFD",
    Details:
      "Designed by a former Google engineer to improve upon Bitcoin's technology, Litecoin offers quicker processing times and a larger number of tokens. It is also the first cryptocurrency to implement SegWit, a method of speeding up transaction times without compromising the underlying blockchain technology.",
  },
  {
    Img: "/digitalcurrency/btc-cash-color.webp",
    Title: "Bitcoin Cash CFD",
    Details:
      "Bitcoin Cash resulted from a hard fork of the Bitcoin blockchain. It increased block size from 1 megabyte to 8 megabytes without incorporating SegWit.",
  },
  {
    Img: "/digitalcurrency/rippleIcon.webp",
    Title: "Ripple CFD",
    Details:
      "Ripple is both a transaction network and crypto token which was created in 2012 as the go-to cryptocurrency for banks and global money transfers, and has recently experienced a period of growth.",
  },
  {
    Img: "/digitalcurrency/eos-icon.webp",
    Title: "EOS CFD",
    Details:
      "EOS is a decentralized operating system based on blockchain technology. It is designed to support of decentralized applications on a commercial-scale by giving all the required core functionalities.",
  },
  {
    Img: "/digitalcurrency/emc-icon.webp",
    Title: "Emercoin CFD",
    Details:
      "Emercoin is an open-source cryptocurrency which originated from Bitcoin, Peercoin and Namecoin. Other than being a cryptocurrency, it is also a platform for secure distributed blockchain business services.",
  },
  {
    Img: "/digitalcurrency/nmc-icon.webp",
    Title: "NameCoin CFD",
    Details:
      "Namecoin is a blockchain protocol that serves as a naming system. Since Namecoin is a fork of Bitcoin, it is also a cryptocurrency that can be used for peer-to-peer transactions.",
  },
  {
    Img: "/digitalcurrency/ppc-icon.webp",
    Title: "PeerCoin CFD",
    Details:
      "PeerCoin aims to solve the inefficiency problem of the Proof-of-Work that is used by bitcoin and many other coins using its own Proof-of-Stake system.",
  },
  {
    Img: "/digitalcurrency/dot-icon.webp",
    Title: "Polkadot CFD",
    Details:
      "Polkadot is a platform that allows diverse blockchains to transfer messages, including value, in a trust-free fashion; sharing their unique features while pooling their security. In brief, Polkadot is a scalable, heterogeneous, multi-chain technology.",
  },
  {
    Img: "/digitalcurrency/xlm-icon.webp",
    Title: "Stellar CFD",
    Details:
      "Stellar, or Stellar Lumens, is an open source, decentralized protocol for digital currency to fiat money low-cost transfers which allows cross-border transactions between any pair of currencies.",
  },
  {
    Img: "/digitalcurrency/lnk-icon.webp",
    Title: "Chainlink CFD",
    Details:
      "Chainlink is a decentralized oracle network and cryptocurrency that provides data to blockchains. It is one of the main sources of data used to feed information to applications in decentralized finance.",
  },
  {
    Img: "/digitalcurrency/dgc-icon.webp",
    Title: "Dogecoin CFD",
    Details:
      "Dogecoin was founded by software engineers Billy Markus and Jackson Palmer, as a payment system. This coin began as a 'meme coin' and is now seen as a popular option for traders.",
  },
  {
    Img: "/digitalcurrency/tzs-icon.webp",
    Title: "Tezos CFD",
    Details:
      "Tezos is a decentralized and Proof of Stake blockchain network that can perform peer-to-peer transactions and assists as a platform to arrange smart contracts.",
  },
  {
    Img: "/digitalcurrency/usp-icon.webp",
    Title: "Uniswap CFD",
    Details:
      "Uniswap is used to exchange cryptocurrencies. It enables automated transactions between cryptocurrency tokens on the Ethereum blockchain through smart contracts.",
  },
  {
    Img: "/digitalcurrency/cdo-icon.webp",
    Title: "Cardano CFD",
    Details:
      "Cardano is a public blockchain platform that enables peer-to-peer transactions with its internal cryptocurrency, Ada. It is open-source and decentralized, with consensus achieved using proof of stake.",
  },
  {
    Img: "/digitalcurrency/bnc-icon.webp",
    Title: "Binance Coin CFD",
    Details:
      "Binance Coin was initially formed as a utility token for reduced trading fees, but its uses have extended to payments for transaction fees (on the Binance Chain), travel bookings, entertainment, online services and financial services.",
  },
  {
    Img: "/digitalcurrency/avalanche-icon.webp",
    Title: "Avalanche CFD",
    Details:
      "Avalanche is a decentralized, open-source proof of stake blockchain platform. It uses smart contracts to support various blockchain-based projects with high transaction processing speed.",
  },
  {
    Img: "/digitalcurrency/luna-icon.webp",
    Title: "Luna CFD",
    Details:
      "One of the native tokens of the Terra network, a blockchain-based project in South Korea. Luna can be used to mint a stablecoin TerraUSD (UST) and maintain Terra stablecoins' price.",
  },
  {
    Img: "/digitalcurrency/polygon-matic-icon.webp",
    Title: "Polygon Matic CFD",
    Details:
      "Ethereum blockchain is used in the Polygon platform, which can connect and evolve Ethereum-compatible projects and blockchains. It uses a modified proof-of-stake consensus mechanism.",
  },
  {
    Img: "/digitalcurrency/moonbeam-icon.webp",
    Title: "Moonbeam CFD",
    Details:
      "An Ethereum-compatible smart contract platform on Polkadot founded by Derek Yoo. It can simplify the process of building and/or deploying Solidity projects in a Substrate-based environment.",
  },
  {
    Img: "/digitalcurrency/kusama-icon.webp",
    Title: "Kusama CFD",
    Details:
      "Kusama utilizes two types of blockchains, the relay chain and parachains in the Polkadot ecosystem. It serves like a sandbox that help testing and developing new features in early projects.",
  },
];

export const Stock = [
  {
    SYMBOL: "AUS200",
    DESCRIPTION: "Australia S&P ASX 200 Index",
    MIN: "0.000",
    AVG: "1.220",
  },
  {
    SYMBOL: "DE40",
    DESCRIPTION: "Germany 40 Index",
    MIN: "0.500",
    AVG: "1.338",
  },
  {
    SYMBOL: "F40",
    DESCRIPTION: "France 40 Index",
    MIN: "0.000",
    AVG: "0.749",
  },
  {
    SYMBOL: "JP225",
    DESCRIPTION: "Japan 225 Index",
    MIN: "6.000",
    AVG: "8.858",
  },
  {
    SYMBOL: "STOXX50",
    DESCRIPTION: "EU Stocks 50 Index",
    MIN: "0.200",
    AVG: "1.760",
  },
  {
    SYMBOL: "UK100",
    DESCRIPTION: "UK 100 Index",
    MIN: "1.000",
    AVG: "2.133",
  },
  {
    SYMBOL: "US30",
    DESCRIPTION: "US Wall Street 30 Index",
    MIN: "1.000",
    AVG: "1.411",
  },
  {
    SYMBOL: "US500",
    DESCRIPTION: "US SPX 500 Index",
    MIN: "0.200",
    AVG: "0.492",
  },
  {
    SYMBOL: "USTEC",
    DESCRIPTION: "US Tech 100 Index",
    MIN: "1.000",
    AVG: "1.807",
  },
  {
    SYMBOL: "CA60",
    DESCRIPTION: "Canada 60 Index",
    MIN: "0.600",
    AVG: "0.600",
  },
  {
    SYMBOL: "CHINA50",
    DESCRIPTION: "FTSE China A50 Index",
    MIN: "3.290",
    AVG: "6.953",
  },
  {
    SYMBOL: "CHINAH",
    DESCRIPTION: "Hong Kong China H-shares Index",
    MIN: "0.000",
    AVG: "2.083",
  },
  {
    SYMBOL: "ES35",
    DESCRIPTION: "Spain 35 Index",
    MIN: "4.200",
    AVG: "4.426",
  },
  {
    SYMBOL: "HK50",
    DESCRIPTION: "Hong Kong 50 Index",
    MIN: "7.000",
    AVG: "8.169",
  },
  {
    SYMBOL: "IT40",
    DESCRIPTION: "Italy 40 Index",
    MIN: "9.000",
    AVG: "9.000",
  },
  {
    SYMBOL: "MidDE50",
    DESCRIPTION: "Germany Mid 50 Index",
    MIN: "7.500",
    AVG: "27.864",
  },
  {
    SYMBOL: "NETH25",
    DESCRIPTION: "Netherlands 25 Index",
    MIN: "0.190",
    AVG: "0.190",
  },
  {
    SYMBOL: "NOR25",
    DESCRIPTION: "Norway 25 Index",
    MIN: "0.680",
    AVG: "0.680",
  },
  {
    SYMBOL: "SA40",
    DESCRIPTION: "South Africa 40 Index",
    MIN: "7.500",
    AVG: "15.444",
  },
  {
    SYMBOL: "SE30",
    DESCRIPTION: "Sweden 30",
    MIN: "0.380",
    AVG: "0.380",
  },
  {
    SYMBOL: "SWI20",
    DESCRIPTION: "Switzerland 20 Index",
    MIN: "3.000",
    AVG: "3.500",
  },
  {
    SYMBOL: "TecDE30",
    DESCRIPTION: "Germany Tech 30 Index",
    MIN: "2.300",
    AVG: "3.172",
  },
  {
    SYMBOL: "US2000",
    DESCRIPTION: "US Small Cap 2000 Index",
    MIN: "0.140",
    AVG: "0.480",
  },
];

export const Commodities = [
  {
    SYMBOL: "BRENT",
    DESCRIPTION: "Brent Crude Oil Futures",
    MIN: "0.020",
    AVG: "0.028",
  },
  {
    SYMBOL: "Cocoa",
    DESCRIPTION: "Cocoa futures",
    MIN: "3.000",
    AVG: "4.608",
  },
  {
    SYMBOL: "Coffee",
    DESCRIPTION: "Coffee Futures",
    MIN: "0.300",
    AVG: "0.300",
  },
  {
    SYMBOL: "Corn",
    DESCRIPTION: "Corn Futures",
    MIN: "0.680",
    AVG: "0.680",
  },
  {
    SYMBOL: "Cotton",
    DESCRIPTION: "Cotton Futures",
    MIN: "0.150",
    AVG: "0.150",
  },
  {
    SYMBOL: "OJ",
    DESCRIPTION: "Orange Juice Futures",
    MIN: "1.120",
    AVG: "1.120",
  },
  {
    SYMBOL: "Soybean",
    DESCRIPTION: "Soybean Futures",
    MIN: "1.350",
    AVG: "1.350",
  },
  {
    SYMBOL: "Sugar",
    DESCRIPTION: "Sugar Futures",
    MIN: "0.030",
    AVG: "0.033",
  },
  {
    SYMBOL: "Wheat",
    DESCRIPTION: "Wheat Futures",
    MIN: "0.750",
    AVG: "0.750",
  },
  {
    SYMBOL: "WTI",
    DESCRIPTION: "West Texas Intermediate - Crude Oil Futures",
    MIN: "0.020",
    AVG: "0.027",
  },
  {
    SYMBOL: "XBRUSD",
    DESCRIPTION: "Brent Crude Oil Spot vs United States Dollar",
    MIN: "0.030",
    AVG: "0.034",
  },
  {
    SYMBOL: "XNGUSD",
    DESCRIPTION: "Natural Gas Spot vs United States Dollar",
    MIN: "0.002",
    AVG: "0.004",
  },
  {
    SYMBOL: "XTIUSD",
    DESCRIPTION: "WTI Crude Oil Spot vs United States Dollar",
    MIN: "0.030",
    AVG: "0.034",
  },
];


export const digitalcurrencyTable = [
  {
    SYMBOL:"BCHUSD",
    DESCRIPTION: "Bitcoin Cash vs United States Dollar CFD",
    MIN: "2.210",
    AVG: "5.839",
  },
  {
    SYMBOL: "BTCUSD",
    DESCRIPTION: "Bitcoin vs United States Dollar CFD",
    MIN: "8.710",
    AVG: "42.036",
  },
  {
    SYMBOL: "DOTUSD",
    DESCRIPTION: "Polkadot vs United States Dollar CFD",
    MIN: "0.011",
    AVG: "0.013",
  },
  {
    SYMBOL: "DSHUSD",
    DESCRIPTION: "Dash Coin vs United States Dollar CFD",
    MIN: "0.000",
    AVG: "1.241",
  },
  {
    SYMBOL: "EMCUSD",
    DESCRIPTION: "Emercoin vs United States Dollar CFD",
    MIN: "0.157",
    AVG: "0.157",
  },
  {
    SYMBOL: "EOSUSD",
    DESCRIPTION: "EOS vs United States Dollar CFD",
    MIN: "0.000",
    AVG: "0.064",
  },
  {
    SYMBOL: "ETHUSD",
    DESCRIPTION: "Ethereum vs United States Dollar CFD",
    MIN: "4.560",
    AVG: "11.605",
  },
  {
    SYMBOL: "LNKUSD",
    DESCRIPTION: "Chainlink vs United States Dollar CFD",
    MIN: "0.012",
    AVG: "0.020",
  },
  {
    SYMBOL: "LTCUSD",
    DESCRIPTION: "Lite Coin vs United States Dollar CFD",
    MIN: "1.050",
    AVG: "1.597",
  },
  {
    SYMBOL: "NMCUSD",
    DESCRIPTION: "NameCoin vs United States Dollar CFD",
    MIN: "7.895",
    AVG: "7.895",
  },
  {
    SYMBOL: "PPCUSD",
    DESCRIPTION: "PeerCoin vs United States Dollar CFD",
    MIN: "0.184",
    AVG: "0.276",
  },
  {
    SYMBOL: "XLMUSD",
    DESCRIPTION: "Stellar vs United States Dollar CFD",
    MIN: "0.000",
    AVG: "0.000",
  },
  {
    SYMBOL: "XRPUSD",
    DESCRIPTION: "Ripple vs United States Dollar CFD",
    MIN: "0.008",
    AVG: "0.020",
  },
  {
    SYMBOL: "ADAUSD",
    DESCRIPTION: "Cardano vs United States Dollar CFD",
    MIN: "0.001",
    AVG: "0.003",
  },
  {
    SYMBOL: "BNBUSD",
    DESCRIPTION: "Binance Smartchain vs United States Dollar CFD",
    MIN: "1.266",
    AVG: "1.415",
  },
  {
    SYMBOL: "DOGUSD",
    DESCRIPTION: "Doge vs United States Dollar CFD",
    MIN: "0.001",
    AVG: "0.001",
  },
  {
    SYMBOL: "UNIUSD",
    DESCRIPTION: "Uniswap vs United States Dollar CFD",
    MIN: "0.061",
    AVG: "0.064",
  },
  {
    SYMBOL: "XTZUSD",
    DESCRIPTION: "Tezos vs United States Dollar CFD",
    MIN: "0.003",
    AVG: "0.026",
  },
];

export const Minor = [
  {
    SYMBOL: "AUDCAD",
    DESCRIPTION: "Australian Dollar vs Canadian Dollar",
    MIN: "0",
    AVG: "0.68",
    MAX: "1",
    MAXAVG: "1.68",
  },
  {
    SYMBOL: "AUDCHF",
    DESCRIPTION: "Australian Dollar vs Swiss Franc",
    MIN: "0",
    AVG: "0.41",
    MAX: "1",
    MAXAVG: "1.41",
  },
  {
    SYMBOL: "AUDJPY",
    DESCRIPTION: "Australian Dollar vs Japanese Yen",
    MIN: "0",
    AVG: "0.5",
    MAX: "1",
    MAXAVG: "1.5",
  },
  {
    SYMBOL: "AUDNZD",
    DESCRIPTION: "Australian Dollar vs New Zealand Dollar",
    MIN: "0",
    AVG: "0.77",
    MAX: "1",
    MAXAVG: "1.77",
  },
  {
    SYMBOL: "CADCHF",
    DESCRIPTION: "Canadian Dollar vs Swiss Franc",
    MIN: "0",
    AVG: "0.58",
    MAX: "1",
    MAXAVG: "1.58",
  },
  {
    SYMBOL: "CADJPY",
    DESCRIPTION: "Canadian Dollar vs Japanese Yen",
    MIN: "0",
    AVG: "0.48",
    MAX: "1",
    MAXAVG: "1.48",
  },
  {
    SYMBOL: "CHFJPY",
    DESCRIPTION: "Swiss Franc vs Japanese Yen",
    MIN: "0.1",
    AVG: "0.86",
    MAX: "1",
    MAXAVG: "1.86",
  },
  {
    SYMBOL: "EURAUD",
    DESCRIPTION: "Euro vs Australian Dollar",
    MIN: "0",
    AVG: "0.8",
    MAX: "1",
    MAXAVG: "1.8",
  },
  {
    SYMBOL: "EURCAD",
    DESCRIPTION: "Euro vs Canadian Dollar",
    MIN: "0",
    AVG: "0.74",
    MAX: "1",
    MAXAVG: "1.74",
  },
  {
    SYMBOL: "EURCHF",
    DESCRIPTION: "Euro vs Swiss Franc",
    MIN: "0",
    AVG: "0.61",
    MAX: "1",
    MAXAVG: "1.61",
  },
  {
    SYMBOL: "EURGBP",
    DESCRIPTION: "Euro vs British Pound",
    MIN: "0",
    AVG: "0.27",
    MAX: "1",
    MAXAVG: "1.27",
  },
  {
    SYMBOL: "EURJPY",
    DESCRIPTION: "Euro vs Japanese Yen",
    MIN: "0",
    AVG: "0.3",
    MAX: "1",
    MAXAVG: "1.3",
  },
  {
    SYMBOL: "EURNZD",
    DESCRIPTION: "Euro vs New Zealand Dollar",
    MIN: "0",
    AVG: "1.32",
    MAX: "1",
    MAXAVG: "2.32",
  },
  {
    SYMBOL: "GBPAUD",
    DESCRIPTION: "British Pound vs Australian Dollar",
    MIN: "0",
    AVG: "1.06",
    MAX: "1",
    MAXAVG: "2.06",
  },
  {
    SYMBOL: "GBPCAD",
    DESCRIPTION: "British Pound vs Canadian Dollar",
    MIN: "0",
    AVG: "1.12",
    MAX: "1",
    MAXAVG: "2.12",
  },
  {
    SYMBOL: "GBPCHF",
    DESCRIPTION: "British Pound vs Swiss Franc",
    MIN: "0",
    AVG: "1.1",
    MAX: "1",
    MAXAVG: "2.1",
  },
  {
    SYMBOL: "GBPJPY",
    DESCRIPTION: "British Pound vs Japanese Yen",
    MIN: "0",
    AVG: "0.82",
    MAX: "1",
    MAXAVG: "1.82",
  },
  {
    SYMBOL: "GBPNZD",
    DESCRIPTION: "British Pound vs New Zealand Dollar",
    MIN: "0.1",
    AVG: "1.98",
    MAX: "1",
    MAXAVG: "2.98",
  },
  {
    SYMBOL: "NZDCAD",
    DESCRIPTION: "New Zealand Dollar vs Canadian Dollar",
    MIN: "0",
    AVG: "1.04",
    MAX: "1",
    MAXAVG: "2.04",
  },
  {
    SYMBOL: "NZDCHF",
    DESCRIPTION: "New Zealand Dollar vs Swiss Franc",
    MIN: "0",
    AVG: "0.73",
    MAX: "1",
    MAXAVG: "1.73",
  },
  {
    SYMBOL: "NZDJPY",
    DESCRIPTION: "New Zealand Dollar vs Japanese Yen",
    MIN: "0",
    AVG: "0.6",
    MAX: "1",
    MAXAVG: "1.6",
  },
];
export const Exotic = [
  {
    SYMBOL: "AUDSGD",
    DESCRIPTION: "Australian Dollar vs Singapore Dollar",
    MIN: "0",
    AVG: "0.97",
    MAX: "1",
    MAXAVG: "1.97",
  },
  {
    SYMBOL: "CHFSGD",
    DESCRIPTION: "Swiss Franc vs Singapore Dollar",
    MIN: "0.3",
    AVG: "2.05",
    MAX: "1",
    MAXAVG: "3.05",
  },
  {
    SYMBOL: "EURDKK",
    DESCRIPTION: "Euro vs Danish Kroner",
    MIN: "10",
    AVG: "11.11",
    MAX: "1",
    MAXAVG: "12.11",
  },
  {
    SYMBOL: "EURHKD",
    DESCRIPTION: "Euro vs Hong Kong Dollar",
    MIN: "0",
    AVG: "2.17",
    MAX: "1",
    MAXAVG: "3.17",
  },
  {
    SYMBOL: "EURNOK",
    DESCRIPTION: "Euro vs Norwegian Kroner",
    MIN: "0.4",
    AVG: "52.89",
    MAX: "1",
    MAXAVG: "53.89",
  },
  {
    SYMBOL: "EURPLN",
    DESCRIPTION: "Euro vs Polish Zloty",
    MIN: "1.8",
    AVG: "21.2",
    MAX: "1",
    MAXAVG: "22.2",
  },
  {
    SYMBOL: "EURSEK",
    DESCRIPTION: "Euro vs Swedish Krona",
    MIN: "0.3",
    AVG: "44.07",
    MAX: "1",
    MAXAVG: "45.07",
  },
  {
    SYMBOL: "EURSGD",
    DESCRIPTION: "Euro vs Singapore Dollar",
    MIN: "0",
    AVG: "0.9",
    MAX: "1",
    MAXAVG: "1.9",
  },
  {
    SYMBOL: "EURTRY",
    DESCRIPTION: "Euro vs Turkish Lira",
    MIN: "0.7",
    AVG: "95.14",
    MAX: "1",
    MAXAVG: "96.14",
  },
  {
    SYMBOL: "EURZAR",
    DESCRIPTION: "Euro vs South African Rand",
    MIN: "10.3",
    AVG: "94.68",
    MAX: "1",
    MAXAVG: "95.68",
  },
  {
    SYMBOL: "GBPDKK",
    DESCRIPTION: "British Pound vs Danish Kroner",
    MIN: "0.6",
    AVG: "18.32",
    MAX: "1",
    MAXAVG: "19.32",
  },
  {
    SYMBOL: "GBPNOK",
    DESCRIPTION: "British Pound vs Norwegian Kroner",
    MIN: "0",
    AVG: "38.14",
    MAX: "1",
    MAXAVG: "39.14",
  },
  {
    SYMBOL: "GBPSEK",
    DESCRIPTION: "British Pound vs Swedish Krona",
    MIN: "2",
    AVG: "28.13",
    MAX: "1",
    MAXAVG: "29.13",
  },
  {
    SYMBOL: "GBPSGD",
    DESCRIPTION: "British Pound vs Singapore Dollar",
    MIN: "0.3",
    AVG: "2.45",
    MAX: "1",
    MAXAVG: "3.45",
  },
  {
    SYMBOL: "GBPTRY",
    DESCRIPTION: "British Pound vs Turkish Lira",
    MIN: "1.2",
    AVG: "138.98",
    MAX: "1",
    MAXAVG: "139.98",
  },
  {
    SYMBOL: "NOKJPY",
    DESCRIPTION: "Norwegian Kroner vs Japanese Yen",
    MIN: "0.1",
    AVG: "0.67",
    MAX: "1",
    MAXAVG: "1.67",
  },
  {
    SYMBOL: "NOKSEK",
    DESCRIPTION: "Norwegian Kroner vs Swedish Krona",
    MIN: "2",
    AVG: "7.53",
    MAX: "1",
    MAXAVG: "8.53",
  },
  {
    SYMBOL: "SEKJPY",
    DESCRIPTION: "Swedish Krona vs Japanese Yen",
    MIN: "0.2",
    AVG: "0.87",
    MAX: "1",
    MAXAVG: "1.87",
  },
  {
    SYMBOL: "SGDJPY",
    DESCRIPTION: "Singapore Dollar vs Japanese Yen",
    MIN: "0",
    AVG: "0.7",
    MAX: "1",
    MAXAVG: "1.7",
  },
  {
    SYMBOL: "USDCNH",
    DESCRIPTION: "United States Dollar vs Chinese RMB",
    MIN: "0",
    AVG: "2.93",
    MAX: "1",
    MAXAVG: "3.93",
  },
  {
    SYMBOL: "USDCZK",
    DESCRIPTION: "United States Dollar vs Czech Republic Koruna",
    MIN: "0",
    AVG: "5.21",
    MAX: "1",
    MAXAVG: "6.21",
  },
  {
    SYMBOL: "USDDKK",
    DESCRIPTION: "United States Dollar vs Danish Kroner",
    MIN: "2.6",
    AVG: "4.77",
    MAX: "1",
    MAXAVG: "5.77",
  },
  {
    SYMBOL: "USDHKD",
    DESCRIPTION: "United States Dollar vs Hong Kong Dollar",
    MIN: "0",
    AVG: "0.89",
    MAX: "1",
    MAXAVG: "1.89",
  },
  {
    SYMBOL: "USDHUF",
    DESCRIPTION: "United States Dollar vs Hungarian Forint",
    MIN: "0",
    AVG: "9.48",
    MAX: "1",
    MAXAVG: "10.48",
  },
  {
    SYMBOL: "USDMXN",
    DESCRIPTION: "United States Dollar vs Mexican Peso",
    MIN: "0",
    AVG: "28.57",
    MAX: "1",
    MAXAVG: "29.57",
  },
  {
    SYMBOL: "USDNOK",
    DESCRIPTION: "United States Dollar vs Norwegian Kroner",
    MIN: "0",
    AVG: "36.79",
    MAX: "1",
    MAXAVG: "37.79",
  },
  {
    SYMBOL: "USDPLN",
    DESCRIPTION: "United States Dollar vs Polish Zloty",
    MIN: "1.6",
    AVG: "15.79",
    MAX: "1",
    MAXAVG: "16.79",
  },
  {
    SYMBOL: "USDRUB",
    DESCRIPTION: "United States Dollar vs Russian Ruble",
    MIN: "4",
    AVG: "65.26",
    MAX: "1",
    MAXAVG: "66.26",
  },
  {
    SYMBOL: "USDSEK",
    DESCRIPTION: "United States Dollar vs Swedish Krona",
    MIN: "0",
    AVG: "30.31",
    MAX: "1",
    MAXAVG: "31.31",
  },
  {
    SYMBOL: "USDTHB",
    DESCRIPTION: "United States Dollar vs Thai Baht",
    MIN: "0",
    AVG: "63.21",
    MAX: "1",
    MAXAVG: "64.21",
  },
  {
    SYMBOL: "USDTRY",
    DESCRIPTION: "United States Dollar vs Turkish Lira",
    MIN: "0.6",
    AVG: "50.61",
    MAX: "1",
    MAXAVG: "51.61",
  },
  {
    SYMBOL: "USDZAR",
    DESCRIPTION: "United States Dollar vs South African Rand",
    MIN: "19",
    AVG: "79.85",
    MAX: "1",
    MAXAVG: "80.85",
  },
  {
    SYMBOL: "USDSGD",
    DESCRIPTION: "United States Dollar vs Singapore Dollar",
    MIN: "0.2",
    AVG: "0.85",
    MAX: "1",
    MAXAVG: "1.85",
  },
];

export const MISSION_VISION_VALUES = {
  mission: {
    title: "Our Mission",
    description:
      "Our mission at Live trading is to establish ourselves as a global leader in online trading, offering access to any financial market, from Forex to Cryptocurrencies. We are committed to innovation and quality, building a reputation as a trusted and reliable partner for traders worldwide.",
    icon: "/path/to/mission-icon.png",
  },
  vision: {
    title: "Our Vision",
    description:
      "Our vision is to empower people with easy and immediate access to financial markets, along with the education and tools necessary for success, irrespective of their experience level. We aim to provide global control over finances, ensuring financial independence for all.",
    icon: "/path/to/vision-icon.png",
  },
  values: [
    {
      image: "/images/about-benefit.svg",
      title: "Innovation",
      description:
        "We continuously provide our clients with the latest and greatest in trading technology, ensuring they have the edge in the markets.",
    },
    {
      image: "/images/about-benefit-2.svg",
      title: "Empowerment",
      description:
        "We empower users of our platform to take control of their finances with the tools and knowledge they need to succeed.",
    },
    {
      image: "/images/afr-contact.webp",
      title: "Client-focus",
      description:
        "Before we do anything, we always think about our users, and how they will benefit.",
    },
    {
      image: "/images/about-benefit.svg",
      title: "Transparency",
      description:
        "We earn the trust of clients by being clear about everything from the very start.",
    },
  ],
};
export const Live_Prices_FX = [
  {
    title: "EURUSD",
    Bid: "1.08231",
    ask: "1.08232",
    Spread: "0.00 Pips",
    img1: "/flag/eu.svg",
    img2: "/flag/us.svg",
  },

  {
    title: "USDJPY",
    Bid: "153.43600",
    ask: "153.44000",
    Spread: "0.30 Pips",
    img1: "/flag/us.svg",
    img2: "/flag/jp.svg",
  },
  {
    title: "AUDUSD",
    Bid: "0.65761",
    ask: "0.65764",
    Spread: "0.20 Pips",
    img1: "/flag/au.svg",
    img2: "/flag/us.svg",
  },
  {
    title: "GBPUSD",
    Bid: "1.29825",
    ask: "1.29827",
    Spread: "0.20 Pips",
    img1: "/flag/gb.svg",
    img2: "/flag/us.svg",
  },
];
export const Live_Prices_Indices = [
  {
    title: "DOW30 / US30",
    Bid: "42465.00",
    ask: "42467.00",
    Spread: "2.00 Pips",
  },
  {
    title: "NASDAQ / NAS100",
    Bid: "20392.60",
    ask: "20394.60",
    Spread: "2.00 Pips",
  },
  {
    title: "German 30 / DAX30",
    Bid: "19624.10",
    ask: "19625.30",
    Spread: "1.20 Pips",
  },
  {
    title: "UK 100 FTSE / UK100",
    Bid: "8329.80",
    ask: "8331.20",
    Spread: "1.40 Pips",
  },
  {
    title: "Euro Stoxx 50 / ESTX50",
    Bid: "4993.70",
    ask: "4995.50",
    Spread: "1.80 Pips",
  },
];
export const Live_Prices_Commodities = [
  {
    title: "Gold / XAUUSD",
    Bid: "2753.79",
    ask: "2753.98",
    Spread: "1.90 Pips",
    // img1:"e";,
    // img2:"df";,
  },
  {
    title: "Silver / XAGUSD",
    Bid: "34.15",
    ask: "34.17",
    Spread: "1.50 Pips",
  },

  {
    title: "West Texas Intermediate / WTI",
    Bid: "67.66",
    ask: "67.77",
    Spread: "1.00 Pips",
  },
  {
    title: "Brent Crude / BRENT",
    Bid: "71.43",
    ask: "71.55",
    Spread: "1.10 Pips",
  },
];
export const Live_Prices_Cryptocurrencies = [
  {
    title: "Bitcoin",
    Bid: "71197.88",
    ask: "71257.91",
    Spread: "600.20 Pips",
  },
  {
    title: "Bitcoin Cash",
    Bid: "381.77",
    ask: "383.88",
    Spread: "21.10 Pips",
  },
  {
    title: "Litecoin",
    Bid: "71.97",
    ask: "72.51",
    Spread: "5.40 Pips",
  },
  {
    title: "Ethereum",
    Bid: "2622.64",
    ask: "2624.52",
    Spread: "18.80 Pips",
  },
  {
    title: "Ripple",
    Bid: "0.52",
    ask: "0.53",
    Spread: "11.40 Pips",
  },
];

export const meta_4_standard = {
  Spread: "1.0 Pips",
  commission: "None",
  Deposit: "No Limit",
  Trade_Size: "0.01 Lots",
  market: "50+ FX Pairs, Crypto, Metals, CFDs",
  leverage: "1000:1",
  balance: "*ACCOUNT BALANCE UP TO 7,000 USD",
  button: "Open MT4 Standard Account",
};
export const meta_4_pro = {
  Spread: "0.0 Pips",
  commission: "$7 per lot",
  Deposit: "No Limit",
  Trade_Size: "0.01 Lots",
  market: "50+ FX Pairs, Crypto, Metals, CFDs",
  leverage: "500:1",
  balance: "*ACCOUNT BALANCE UP TO 50,000 USD",
  button: " Open MT4 Pro Account",
};

export const meta_5_standard = {
  Spread: "1.0 Pips",
  commission: "None",
  Deposit: "No Limit",
  Trade_Size: "0.01 Lots",
  market: "50+ FX Pairs, Crypto, Metals, CFDs",
  leverage: " 1000:1",
  balance: "*ACCOUNT BALANCE UP TO 7,000 USD",
  button: "Open MT5 Standard Account",
};

export const meta_5_pro = {
  Spread: "0.0 Pips",
  commission: "$7 per lot",
  Deposit: "No Limit",
  Trade_Size: "0.01 Lots",
  market: "50+ FX Pairs, Crypto, Metals, CFDs",
  leverage: "500:1",
  balance: "*ACCOUNT BALANCE UP TO 50,000 USD",
  button: "Open MT5 Pro Account",
};

export const Why_trade_with_us = [
  {
    id: "1",
    title: "Lightning-fast Execution",
    description:
      "Experience lightning-fast trade execution with our state-of-the-art servers located in the NY4 and TY3 data centres in New York and Tokyo.",
    Icon: BsLightningChargeFill,
  },
  {
    id: "2",
    title: "Low trading costs",
    description:
      "Lower your trading costs by taking advantage of our competitive spreads, which start as low as 0.0, along with our zero and low commission account options.",
    Icon: FaArrowDown,
  },
  {
    id: "3",
    title: "Top Security",
    description:
      "Rest assured that all funds received from our customers are securely deposited and held in our segregated trust account, subject to rigorous oversight by our legal department.",
    Icon: IoMdLock,
  },
  {
    id: "4",
    title: "Regulated Broker",
    description:
      "MYFX Markets operates under the trading name of AXIS INC, an entity regulated by the Registrar of International Business Companies with registration number 24078 IBC2017.",
    Icon: MdOutlineVerifiedUser,
  },

  {
    id: "5",
    title: "Exceptional customer care ",
    description:
      "Get top-notch support from our team of experienced client service professionals.",
    Icon: FaUserAstronaut,
  },
  {
    id: "6",
    title: "Any EA",
    description:
      "We welcome Third-Party Expert Advisors (EAs) and MT4/MT5 plugins to enhance your automated trading experience with convenience.",
    Icon: FaRobot,
  },
];
export const perks = [
  {
    icon: Icons.auth,
    title: "Sign Up",
    info: "Create your free account to get started with Astra.",
  },
  {
    icon: Icons.customize,
    title: "Customize",
    info: "Choose a template and customize it to fit your needs.",
  },
  {
    icon: Icons.launch,
    title: "Launch",
    info: "Publish your website and share it with the world.",
  },
];

export const features = [
  {
    icon: Icons.bolt,
    title: "Fast Setup",
    info: "Get your website up and running in minutes with our intuitive AI-powered builder.",
  },
  {
    icon: Icons.palette,
    title: "Customizable Templates",
    info: "Choose from a variety of stunning templates and customize them to suit your brand.",
  },
  {
    icon: Icons.seo,
    title: "SEO Optimized",
    info: "Built-in SEO features ensure your website ranks well on search engines.",
  },
  {
    icon: Icons.monitor,
    title: "Responsive Design",
    info: "Your website will look great on any device, from desktops to mobile phones.",
  },
  {
    icon: Icons.shop,
    title: "E-Commerce Ready",
    info: "Start selling online with our e-commerce features and integrations.",
  },
  {
    icon: Icons.server,
    title: "Secure Hosting",
    info: "Enjoy peace of mind with secure and reliable hosting for your website.",
  },
];
export const WHY_CHOOSE_LIVETRADING = [
  {
    title: "Advanced Trading Technology",
    description:
      "Experience seamless trading with our state-of-the-art technology, designed to handle the demands of high-frequency and large-scale trading. Our platform offers lightning-fast order execution, ensuring you never miss an opportunity.",
  },
  {
    title: "Wide Range of Markets",
    description:
      "Diversify your portfolio with access to multiple markets. Live trading provides a vast array of trading instruments, including Forex, cryptocurrencies, commodities, indices, and more. Whether you're looking to trade Bitcoin or Gold, we've got you covered.",
  },
  {
    title: "User-Friendly Interface",
    description:
      "Our platform is designed with you in mind. Whether you're a seasoned trader or just starting, our intuitive interface makes it easy to manage your trades, monitor market trends, and execute strategies with confidence.",
  },
  {
    title: "Leverage Up to 100x",
    description:
      "Amplify your trading potential with our leverage options. Live trading offers up to 100x leverage on various assets, allowing you to optimize your positions and increase your returns. With great power comes great responsibility—trade wisely.",
  },
  {
    title: "Secure and Reliable",
    description:
      "Your security is our priority. Live trading employs industry-leading security protocols, including advanced encryption and two-factor authentication (2FA), to protect your assets and personal information. Trade with peace of mind knowing your investments are safe.",
  },
  {
    title: "Innovative Trading Tools",
    description:
      "Take advantage of our cutting-edge trading tools. Live trading offers advanced charting software, technical analysis tools, and real-time market data, giving you the edge you need to stay ahead in volatile markets.",
  },
];

export const HOW_TO_GET_STARTED = [
  {
    step: "Sign Up",
    url: "/register",
    description:
      "Create an account with Live trading in just a few clicks. All you need is an email address to get started.",
  },
  {
    step: "Fund Your Account",
    url: "/forgot_password",
    description:
      "Deposit funds using our secure payment methods. We support a variety of currencies and payment options for your convenience.",
  },
  {
    step: "Start Trading",
    url: "/login",
    description:
      "Once your account is funded, you’re ready to start trading. Choose your markets, set your strategies, and begin your journey to financial freedom.",
  },
];

export const pricingCards = [
  {
    title: "Starter",
    description: "Perfect for trying out plura",
    price: "Free",
    duration: "",
    highlight: "Key features",
    buttonText: "Start for free",
    features: ["Limited projects", "1 Team member", "Basic features"],
    priceId: "",
  },
  {
    title: "Unlimited Saas",
    description: "The ultimate agency kit",
    price: "$199",
    duration: "month",
    highlight: "Key features",
    buttonText: "Upgrade to Pro",
    features: [
      "Unlimited projects",
      "5 Team members",
      "Advanced design tools",
      "Customizable domain",
    ],
    priceId: "price_1OYxkqFj9oKEERu1KfJGWxgN",
  },
  {
    title: "Enterprise",
    description: "For serious agency owners",
    price: "$399",
    duration: "month",
    highlight: "Everything in Starter, plus",
    buttonText: "Upgrade to Enterprise",
    features: [
      "Unlimited projects",
      "Unlimited Team members",
      "Custom branding",
      "Priority support (24/7)",
    ],
    priceId: "price_1OYxkqFj9oKEERu1NbKUxXxN",
  },
];

export const bentoCards = [
  {
    title: "Start with Inspiration",
    info: "Browse our vast library of pre-designed templates or upload your own images.",
    imgSrc: "/assets/bento-1.svg", // Lightbulb or Inspiration icon
    alt: "Inspiration for website creation",
  },
  {
    title: "AI Assists Your Vision",
    info: "Our intelligent AI tailors suggestions and functionalities based on your goals.",
    imgSrc: "/assets/bento1.svg", // AI Assistant icon
    alt: "AI website building assistant",
  },
  {
    title: "Drag & Drop Customization",
    info: "Effortlessly personalize your website with our intuitive drag-and-drop editor.",
    imgSrc: "/assets/bento1.svg", // Drag and Drop icon or hand editing a website
    alt: "Website customization with drag and drop",
  },
  {
    title: "Launch & Shine Online",
    info: "Publish your website with a single click and take your brand to the world.",
    imgSrc: "/assets/bento1.svg", // Rocket launching or website going live
    alt: "Website launch and publication",
  },
];

export const reviews = [
  {
    name: "Jack",
    username: "@jack",
    body: "I've never seen anything like this before. It's amazing. I love it.",
  },
  {
    name: "Jill",
    username: "@jill",
    body: "I don't know what to say. I'm speechless. This is amazing.",
  },
  {
    name: "John",
    username: "@john",
    body: "I'm at a loss for words. This is amazing. I love it.",
  },
  {
    name: "Jane",
    username: "@jane",
    body: "I'm at a loss for words. This is amazing. I love it.",
  },
  {
    name: "Jenny",
    username: "@jenny",
    body: "I'm at a loss for words. This is amazing. I love it.",
  },
  {
    name: "James",
    username: "@james",
    body: "I'm at a loss for words. This is amazing. I love it.",
  },
];
export const liveTraders = [
  {
    heroImage: "/Livetraders/hero.jpg",
    benefitsImage: "/Livetraders/benefit.jpg",
    signalImage: "/Livetraders/signal.png",
    reasonImage: "/Livetraders/reasons.jpg",
  },
];

export const mobile_trading = [
  {
    title: "Powerful platform tools powered by TradingView",
    description:
      "Over 100 popular technical indicators and the ability to analyze price trends, with chart time intervals starting from five seconds. Automate trading strategies using our APIs",
    img: "/trader/powerful.webp",
    linkTitle: "Discover Tradingview tools",
    url: "/#",
  },
  {
    title: "Developer portal",
    description:
      "Our developer portal is packed with useful trading resources, powerful APIs, development guides and more.",
    img: "/trader/dev.webp",
    linkTitle: "View developer portal",
    url: "/#",
  },
];

export const offers = [
  {
    title: "Powerful trading tools",
    description:
      "We offer you a range of powerful analysis tools to enhance your trading strategies, including Advanced charts powered by TradingView, Technical Analysis from Autochartist and the Economic overlay.",
    linkTitle: "See our trading tools",
    img: "/trader/api.webp",
    url: "/#",
  },
  {
    title: "Over 68 forex pairs",
    description:
      "We offer forex online trading with tight spreads on all the major and minor currency pairs, nearly 24 hours a day, five days a week. Trade forex pairs using our powerful OANDA Trade platform, MT4 and TradingView.",
    linkTitle: "See FX pairs",
    img: "/trader/broker.webp",
    url: "/#",
  },
  {
    title: "Trade popular crypto",
    description:
      "Through our partnership with Paxos, you can trade the big names in crypto like Bitcoin and Ethereum with our user-friendly app. Super low commissions, no wallet needed and no mark-up when you buy or sell crypto.",
    linkTitle: "Explore crypto trading",
    img: "/trader/meta.webp",
    url: "/#",
  },
];

export const Everything_you_need_to_trade_smarter = [
  {
    title: "Powerful trading tools",
    description:
      "We offer you a range of powerful analysis tools to enhance your trading strategies, including Advanced charts powered by TradingView, Technical Analysis from Autochartist and the Economic overlay.",
    img: "/trader/trading_tool.webp",
    linkTitle: "See our trading tools",
    url: "/#",
  },
  {
    title: "Over 68 forex pairs",
    description:
      "We offer forex online trading with tight spreads on all the major and minor currency pairs, nearly 24 hours a day, five days a week. Trade forex pairs using our powerful OANDA Trade platform, MT4 and TradingView.",
    img: "/trader/forex_repair.webp",
    linkTitle: "See FX pairs",
    url: "#",
  },
  {
    title: "Trade popular crypto",
    description:
      "Through our partnership with Paxos, you can trade the big names in crypto like Bitcoin and Ethereum with our user-friendly app. Super low commissions, no wallet needed and no mark-up when you buy or sell crypto.",
    img: "/trader/popular_crypto.webp",
    linkTitle: "Explore crypto trading",
    url: "#",
  },
];
export const Steps = [
  {
    title: "1. Sign up for an account",
    description:
      "Fill out the form below to register for the Elite Trader program",
    img: "/Livetraders/icon1.webp",
  },
  {
    title: "2. Qualify as an Elite Trader",
    description:
      "Meet our minimum trade volume requirement of US$10,000,000 each calendar month.",
    img: "/Livetraders/icon2.webp",
  },
  {
    title: "3. Benefit from our elite trading program",
    description:
      "Start enjoying the rewards. The more you trade, the more you earn.",
    img: "/Livetraders/icon3.webp",
  },
];

export const TESTIMONIALS = [
  {
    name: "Sophia L.",
    title: "Experienced Trader",
    message:
      "Live trading has completely transformed the way I trade. The platform's intuitive interface and advanced tools allow me to execute trades quickly and efficiently. The leverage options have given me the flexibility to maximize my returns, and I feel secure knowing my assets are well-protected.",
    image: "/images/testimonials/sophia.jpg", // Assuming you have a corresponding image
  },
  {
    name: "David R.",
    title: "Crypto Enthusiast",
    message:
      "I've been trading cryptocurrencies for years, and Live trading is by far the best platform I've used. The real-time market data and advanced charting tools help me stay ahead of the market. Plus, the 24/7 support team is always there when I need assistance.",
    image: "/images/testimonials/david.jpg",
  },
  {
    name: "Emma W.",
    title: "New Trader",
    message:
      "As someone new to trading, I was intimidated at first, but Live trading made it easy to get started. The copy trading feature allowed me to learn from experienced traders, and now I'm confident in making my own trades. The educational resources are top-notch!",
    image: "/images/testimonials/emma.jpg",
  },
  {
    name: "Michael B.",
    title: "Forex Trader",
    message:
      "Live trading offers everything I need for successful Forex trading. The platform is reliable, and the execution speed is incredible. The ability to customize my dashboard means I can focus on the metrics that matter most to me. Highly recommended for serious traders!",
    image: "/images/testimonials/michael.jpg",
  },
  {
    name: "Linda K.",
    title: "Investor",
    message:
      "I've used several trading platforms in the past, but Live trading stands out with its comprehensive features and user-friendly design. The margin trading feature has helped me make the most of my investments, and the market insights keep me informed every day.",
    image: "/images/testimonials/linda.jpg",
  },
];

export const NYSE_Stocks = [
  { Symbol: "A.NYSE", stock: "Agilent Technologies Inc" },
  { Symbol: "AA.NYSE", stock: "Alcoa Corp" },
  { Symbol: "AAP.NYSE", stock: "Advance Auto Parts" },
  { Symbol: "AAT.NYSE", stock: "American Assets Trust Inc" },
  { Symbol: "AB.NYSE", stock: "AllianceBernstein Holding LP" },
  { Symbol: "ABB.NYSE", stock: "ABB Ltd" },
  { Symbol: "ABC.NYSE", stock: "AmerisourceBergen Corp" },
  { Symbol: "ABEV.NYSE", stock: "Ambev SA" },
  { Symbol: "ABG.NYSE", stock: "Asbury Automotive Group Inc" },
  { Symbol: "ABM.NYSE", stock: "ABM Industries Inc" },
  { Symbol: "ABR.NYSE", stock: "Arbor Realty Trust Inc" },
  { Symbol: "ABT.NYSE", stock: "Abbott Laboratories" },
  { Symbol: "ABX.NYSE", stock: "Barrick Gold Corp" },
  { Symbol: "ACC.NYSE", stock: "American Campus Communities Inc" },
  { Symbol: "ACCO.NYSE", stock: "ACCO Brands Corp" },
  { Symbol: "ACH.NYSE", stock: "Aluminum Corporation of China Limited" },
  { Symbol: "ACM.NYSE", stock: "AECOM" },
  { Symbol: "ACN.NYSE", stock: "Accenture Plc" },
  { Symbol: "ACP.NYSE", stock: "Aberdeen Income Credit Strategies Fund" },
  { Symbol: "ACRE.NYSE", stock: "Ares Commercial Real Estate Corp" },
  { Symbol: "ADC.NYSE", stock: "Agree Realty Corp" },
  { Symbol: "ADM.NYSE", stock: "Archer-Daniels-Midland Co" },
  { Symbol: "ADNT.NYSE", stock: "Adient Plc" },
  { Symbol: "ADS.NYSE", stock: "Alliance Data Systems Corporation" },
  { Symbol: "ADT.NYSE", stock: "ADT Inc" },
  { Symbol: "AEP.NYSE", stock: "American Electric Power Co Inc" },
  { Symbol: "AER.NYSE", stock: "Aercap Holdings N.V." },
  { Symbol: "AES.NYSE", stock: "The AES Corporation" },
  { Symbol: "AET.NYSE", stock: "Aetna Inc" },
  { Symbol: "AFG.NYSE", stock: "American Financial Group Inc" },
  { Symbol: "AFL.NYSE", stock: "Aflac Inc" },
  { Symbol: "AG.NYSE", stock: "First Majestic Silver Corp" },
  { Symbol: "AGCO.NYSE", stock: "AGCO Corporation" },
  { Symbol: "AGN.NYSE", stock: "Allergan" },
  { Symbol: "AIG.NYSE", stock: "American International Group, Inc." },
  { Symbol: "AIV.NYSE", stock: "Apartment Investment and Management Company" },
  { Symbol: "AIZ.NYSE", stock: "Assurant Inc" },
  { Symbol: "AJG.NYSE", stock: "Arthur J. Gallagher & Co." },
  { Symbol: "AKAM.NYSE", stock: "Akamai Technologies" },
  { Symbol: "ALB.NYSE", stock: "Albemarle Corporation" },
  { Symbol: "ALGN.NYSE", stock: "Align Technology Inc" },
  { Symbol: "ALK.NYSE", stock: "Alaska Air Group, Inc." },
  { Symbol: "ALL.NYSE", stock: "The Allstate Corporation" },
  { Symbol: "ALLE.NYSE", stock: "Allegion PLC" },
  { Symbol: "AM.NYSE", stock: "Ansys Inc" },
  { Symbol: "AMAT.NYSE", stock: "Applied Materials, Inc." },
  { Symbol: "AMCR.NYSE", stock: "Amcor Plc" },
  { Symbol: "AMD.NYSE", stock: "Advanced Micro Devices, Inc." },
  { Symbol: "AME.NYSE", stock: "Ametek Inc." },
  { Symbol: "AMG.NYSE", stock: "Affiliated Managers Group, Inc." },
  { Symbol: "AMH.NYSE", stock: "American Homes 4 Rent" },
  { Symbol: "AMP.NYSE", stock: "Ameriprise Financial, Inc." },
  { Symbol: "AMT.NYSE", stock: "American Tower Corporation" },
  { Symbol: "AMZN.NYSE", stock: "Amazon.com Inc" },
  { Symbol: "AN.NYSE", stock: "AutoNation Inc" },
  { Symbol: "AON.NYSE", stock: "Aon Plc" },
  { Symbol: "APA.NYSE", stock: "APA Corporation" },
  { Symbol: "APD.NYSE", stock: "Air Products and Chemicals, Inc." },
  { Symbol: "APH.NYSE", stock: "Amphenol Corporation" },
  { Symbol: "APTV.NYSE", stock: "Aptiv PLC" },
  { Symbol: "AR.NYSE", stock: "Antero Resources Corporation" },
  { Symbol: "ARE.NYSE", stock: "Alexandria Real Estate Equities, Inc." },
  { Symbol: "ATVI.NYSE", stock: "Activision Blizzard Inc" },
  { Symbol: "AXP.NYSE", stock: "American Express Company" },
  { Symbol: "BA.NYSE", stock: "Boeing Co" },
  { Symbol: "BAC.NYSE", stock: "Bank of America Corp" },
  { Symbol: "BAX.NYSE", stock: "Baxter International Inc" },
  { Symbol: "BB.NYSE", stock: "BlackBerry Ltd" },
  { Symbol: "BBD.NYSE", stock: "Banco Bradesco S.A." },
  { Symbol: "BBY.NYSE", stock: "Best Buy Co., Inc." },
  { Symbol: "BHC.NYSE", stock: "Bausch Health Companies Inc" },
  { Symbol: "BIIB.NYSE", stock: "Biogen Inc" },
  { Symbol: "BK.NYSE", stock: "The Bank of New York Mellon Corporation" },
  { Symbol: "BKR.NYSE", stock: "Baker Hughes Company" },
  { Symbol: "BLK.NYSE", stock: "BlackRock, Inc." },
  { Symbol: "BMY.NYSE", stock: "Bristol Myers Squibb Company" },
  { Symbol: "BR.NYSE", stock: "Broadridge Financial Solutions, Inc." },
  { Symbol: "BSX.NYSE", stock: "Boston Scientific Corporation" },
  { Symbol: "BWA.NYSE", stock: "BorgWarner Inc." },
  { Symbol: "C.NYSE", stock: "Citigroup Inc" },
  { Symbol: "CAG.NYSE", stock: "Conagra Brands, Inc." },
  { Symbol: "CAT.NYSE", stock: "Caterpillar Inc" },
  { Symbol: "CB.NYSE", stock: "Chubb Limited" },
  { Symbol: "CBRE.NYSE", stock: "CBRE Group, Inc." },
  { Symbol: "CCI.NYSE", stock: "Crown Castle Inc" },
  { Symbol: "CCL.NYSE", stock: "Carnival Corporation" },
  { Symbol: "CDAY.NYSE", stock: "Ceridian HCM Holding Inc." },
  { Symbol: "CE.NYSE", stock: "Celanese Corporation" },
  { Symbol: "CELG.NYSE", stock: "Celgene Corporation" },
  { Symbol: "CERN.NYSE", stock: "Cerner Corporation" },
  { Symbol: "CF.NYSE", stock: "CF Industries Holdings, Inc." },
  { Symbol: "CHD.NYSE", stock: "Church & Dwight Co., Inc." },
  { Symbol: "CHKP.NYSE", stock: "Check Point Software Technologies Ltd." },
  { Symbol: "CHRW.NYSE", stock: "C.H. Robinson Worldwide, Inc." },
  { Symbol: "CII.NYSE", stock: "BlackRock Enhanced Equity Dividend Trust" },
  { Symbol: "CL.NYSE", stock: "Colgate-Palmolive Company" },
  { Symbol: "CLX.NYSE", stock: "Clorox Company" },
  { Symbol: "CM.NYSE", stock: "Canadian Imperial Bank of Commerce" },
  { Symbol: "CMA.NYSE", stock: "Comerica Incorporated" },
  { Symbol: "CMG.NYSE", stock: "Chipotle Mexican Grill, Inc." },
  { Symbol: "CMI.NYSE", stock: "Cummins Inc." },
  { Symbol: "CMS.NYSE", stock: "CMS Energy Corporation" },
  { Symbol: "CNC.NYSE", stock: "Centene Corporation" },
  { Symbol: "CNP.NYSE", stock: "CenterPoint Energy, Inc." },
  { Symbol: "COF.NYSE", stock: "Capital One Financial Corporation" },
  { Symbol: "COG.NYSE", stock: "Cabot Oil & Gas Corporation" },
  { Symbol: "COH.NYSE", stock: "Coach, Inc." },
  { Symbol: "COL.NYSE", stock: "Rockwell Collins, Inc." },
  { Symbol: "COP.NYSE", stock: "ConocoPhillips" },
  { Symbol: "COST.NYSE", stock: "Costco Wholesale Corporation" },
  { Symbol: "COTY.NYSE", stock: "Coty Inc" },
  { Symbol: "CPB.NYSE", stock: "Campbell Soup Company" },
  { Symbol: "CRM.NYSE", stock: "Salesforce, Inc." },
  { Symbol: "CS.NYSE", stock: "Credit Suisse Group AG" },
  { Symbol: "CSX.NYSE", stock: "CSX Corporation" },
  { Symbol: "CTAS.NYSE", stock: "Cintas Corporation" },
  { Symbol: "CTSH.NYSE", stock: "Cognizant Technology Solutions Corporation" },
  { Symbol: "CTVA.NYSE", stock: "Corteva, Inc." },
  { Symbol: "CVS.NYSE", stock: "CVS Health Corporation" },
  { Symbol: "CVX.NYSE", stock: "Chevron Corporation" },
  { Symbol: "D.NYSE", stock: "Dominion Energy, Inc." },
  { Symbol: "DAL.NYSE", stock: "Delta Air Lines, Inc." },
  { Symbol: "DD.NYSE", stock: "DuPont de Nemours, Inc." },
  { Symbol: "DE.NYSE", stock: "Deere & Company" },
  { Symbol: "DFS.NYSE", stock: "Discover Financial Services" },
  { Symbol: "DG.NYSE", stock: "Dollar General Corporation" },
  { Symbol: "DHR.NYSE", stock: "Danaher Corporation" },
  { Symbol: "DIS.NYSE", stock: "The Walt Disney Company" },
  { Symbol: "DISH.NYSE", stock: "Dish Network Corporation" },
  { Symbol: "DLR.NYSE", stock: "Digital Realty Trust, Inc." },
  { Symbol: "DOW.NYSE", stock: "Dow Inc." },
  { Symbol: "DTE.NYSE", stock: "DTE Energy Company" },
  { Symbol: "DUK.NYSE", stock: "Duke Energy Corporation" },
  { Symbol: "DVN.NYSE", stock: "Devon Energy Corporation" },
  { Symbol: "DXC.NYSE", stock: "DXC Technology Company" },
  { Symbol: "E.NYSE", stock: "Eni S.p.A." },
  { Symbol: "EA.NYSE", stock: "Electronic Arts Inc." },
  { Symbol: "EBAY.NYSE", stock: "eBay Inc." },
  { Symbol: "ECL.NYSE", stock: "Ecolab Inc." },
  { Symbol: "ED.NYSE", stock: "Consolidated Edison, Inc." },
  { Symbol: "EFX.NYSE", stock: "Equifax Inc." },
  { Symbol: "EIX.NYSE", stock: "Edison International" },
  { Symbol: "EL.NYSE", stock: "Estee Lauder Companies Inc" },
  { Symbol: "EMR.NYSE", stock: "Emerson Electric Co." },
  { Symbol: "ENB.NYSE", stock: "Enbridge Inc." },
  { Symbol: "EOG.NYSE", stock: "EOG Resources, Inc." },
  { Symbol: "EPD.NYSE", stock: "Enterprise Products Partners L.P." },
  { Symbol: "EQH.NYSE", stock: "Equitable Holdings, Inc." },
  { Symbol: "EQR.NYSE", stock: "Equity Residential" },
  { Symbol: "ES.NYSE", stock: "Eversource Energy" },
  { Symbol: "ESS.NYSE", stock: "Essex Property Trust, Inc." },
  { Symbol: "ET.NYSE", stock: "Energy Transfer LP" },
  { Symbol: "ETN.NYSE", stock: "Eaton Corporation PLC" },
  { Symbol: "ETR.NYSE", stock: "Entergy Corporation" },
  { Symbol: "EV.NYSE", stock: "Eaton Vance Corporation" },
  { Symbol: "EXC.NYSE", stock: "Exelon Corporation" },
  { Symbol: "EXP.NYSE", stock: "Eagle Materials Inc." },
  { Symbol: "EXPE.NYSE", stock: "Expedia Group, Inc." },
  { Symbol: "EXR.NYSE", stock: "Extra Space Storage, Inc." },
  { Symbol: "F.NYSE", stock: "Ford Motor Company" },
  { Symbol: "FAST.NYSE", stock: "Fastenal Company" },
  { Symbol: "FCX.NYSE", stock: "Freeport-McMoRan Inc." },
  { Symbol: "FDX.NYSE", stock: "FedEx Corporation" },
  { Symbol: "FE.NYSE", stock: "FirstEnergy Corp." },
  { Symbol: "FFIV.NYSE", stock: "F5, Inc." },
  { Symbol: "FIS.NYSE", stock: "FIS" },
  { Symbol: "FISV.NYSE", stock: "Fiserv, Inc." },
  { Symbol: "FL.NYSE", stock: "Foot Locker Inc." },
  { Symbol: "FLIR.NYSE", stock: "FLIR Systems, Inc." },
  { Symbol: "FLS.NYSE", stock: "Flowserve Corporation" },
  { Symbol: "FMX.NYSE", stock: "Fomento Economico Mexicano S.A.B. de C.V." },
  { Symbol: "FOXA.NYSE", stock: "Fox Corporation" },
  { Symbol: "FOXB.NYSE", stock: "Fox Corporation" },
  { Symbol: "FRC.NYSE", stock: "First Republic Bank" },
  { Symbol: "FTI.NYSE", stock: "TechnipFMC" },
  { Symbol: "FTV.NYSE", stock: "Fortive Corporation" },
  { Symbol: "GD.NYSE", stock: "General Dynamics Corporation" },
  { Symbol: "GE.NYSE", stock: "General Electric Company" },
  { Symbol: "GILD.NYSE", stock: "Gilead Sciences, Inc." },
  { Symbol: "GIS.NYSE", stock: "General Mills, Inc." },
  { Symbol: "GLW.NYSE", stock: "Corning Inc." },
  { Symbol: "GM.NYSE", stock: "General Motors Company" },
  { Symbol: "GOOG.NYSE", stock: "Alphabet Inc." },
  { Symbol: "GOOGL.NYSE", stock: "Alphabet Inc." },
  { Symbol: "GS.NYSE", stock: "Goldman Sachs Group, Inc." },
  { Symbol: "GT.NYSE", stock: "Goodyear Tire & Rubber Company" },
  { Symbol: "GWW.NYSE", stock: "W.W. Grainger, Inc." },
  { Symbol: "HAL.NYSE", stock: "Halliburton Company" },
  { Symbol: "HAS.NYSE", stock: "Hasbro, Inc." },
  { Symbol: "HBAN.NYSE", stock: "Huntington Bancshares Incorporated" },
  { Symbol: "HCA.NYSE", stock: "HCA Healthcare, Inc." },
  { Symbol: "HD.NYSE", stock: "Home Depot, Inc." },
  { Symbol: "HON.NYSE", stock: "Honeywell International Inc." },
  { Symbol: "HPE.NYSE", stock: "Hewlett Packard Enterprise" },
  { Symbol: "HPQ.NYSE", stock: "HP Inc." },
  { Symbol: "HRL.NYSE", stock: "Hormel Foods Corporation" },
  { Symbol: "HSBC.NYSE", stock: "HSBC Holdings Plc" },
  { Symbol: "HST.NYSE", stock: "Host Hotels & Resorts, Inc." },
  { Symbol: "HUM.NYSE", stock: "Humana Inc." },
  { Symbol: "IBM.NYSE", stock: "International Business Machines Corporation" },
  { Symbol: "ICE.NYSE", stock: "Intercontinental Exchange, Inc." },
  { Symbol: "IDXX.NYSE", stock: "IDEXX Laboratories, Inc." },
  { Symbol: "IFF.NYSE", stock: "International Flavors & Fragrances, Inc." },
  { Symbol: "ILMN.NYSE", stock: "Illumina, Inc." },
  { Symbol: "INCY.NYSE", stock: "Incyte Corporation" },
  { Symbol: "INTC.NYSE", stock: "Intel Corporation" },
  { Symbol: "INTU.NYSE", stock: "Intuit Inc." },
  { Symbol: "IP.NYSE", stock: "International Paper Company" },
  { Symbol: "IPG.NYSE", stock: "Interpublic Group of Companies, Inc." },
  { Symbol: "IQV.NYSE", stock: "IQVIA Holdings Inc." },
  { Symbol: "IR.NYSE", stock: "Ingersoll Rand Inc." },
  { Symbol: "IRM.NYSE", stock: "Iron Mountain Incorporated" },
  { Symbol: "ISRG.NYSE", stock: "Intuitive Surgical, Inc." },
  { Symbol: "IT.NYSE", stock: "Gartner, Inc." },
  { Symbol: "ITW.NYSE", stock: "Illinois Tool Works, Inc." },
  { Symbol: "IVZ.NYSE", stock: "Invesco Ltd." },
  { Symbol: "J.NYSE", stock: "JPMorgan Chase & Co." },
  { Symbol: "JCI.NYSE", stock: "Johnson Controls International plc" },
  { Symbol: "JNJ.NYSE", stock: "Johnson & Johnson" },
  { Symbol: "JPM.NYSE", stock: "JPMorgan Chase & Co." },
  { Symbol: "K.NYSE", stock: "Kroger Co." },
  { Symbol: "KHC.NYSE", stock: "Kraft Heinz Company" },
  { Symbol: "KLAC.NYSE", stock: "KLA Corporation" },
  { Symbol: "KO.NYSE", stock: "Coca-Cola Company" },
  { Symbol: "KR.NYSE", stock: "Kroger Co." },
  { Symbol: "L.NYSE", stock: "Loews Corporation" },
  { Symbol: "LH.NYSE", stock: "Laboratory Corporation of America Holdings" },
  { Symbol: "LLY.NYSE", stock: "Eli Lilly and Co." },
  { Symbol: "LMT.NYSE", stock: "Lockheed Martin Corporation" },
  { Symbol: "LOW.NYSE", stock: "Lowe's Companies, Inc." },
  { Symbol: "LRCX.NYSE", stock: "Lam Research Corporation" },
  { Symbol: "LU.NYSE", stock: "Lumen Technologies, Inc." },
  { Symbol: "LUV.NYSE", stock: "Southwest Airlines Co." },
  { Symbol: "M.NYSE", stock: "MetLife, Inc." },
  { Symbol: "MA.NYSE", stock: "Mastercard Incorporated" },
  { Symbol: "MAA.NYSE", stock: "Mid-America Apartment Communities, Inc." },
  { Symbol: "MAC.NYSE", stock: "Macerich Company" },
  { Symbol: "MAR.NYSE", stock: "Marriott International, Inc." },
  { Symbol: "MAS.NYSE", stock: "Masco Corporation" },
  { Symbol: "MCD.NYSE", stock: "McDonald's Corporation" },
  { Symbol: "MCK.NYSE", stock: "McKesson Corporation" },
  { Symbol: "MDT.NYSE", stock: "Medtronic Plc" },
  { Symbol: "MET.NYSE", stock: "MetLife, Inc." },
  { Symbol: "MFG.NYSE", stock: "Mizuho Financial Group, Inc." },
  { Symbol: "MGNX.NYSE", stock: "MacroGenics, Inc." },
  { Symbol: "MMM.NYSE", stock: "3M Company" },
  { Symbol: "MO.NYSE", stock: "Altria Group, Inc." },
  { Symbol: "MON.NYSE", stock: "Monsanto Company" },
  { Symbol: "MPWR.NYSE", stock: "Monolithic Power Systems, Inc." },
  { Symbol: "MRK.NYSE", stock: "Merck & Co., Inc." },
  { Symbol: "MS.NYSE", stock: "Morgan Stanley" },
  { Symbol: "MSFT.NYSE", stock: "Microsoft Corporation" },
  { Symbol: "MU.NYSE", stock: "Micron Technology, Inc." },
  { Symbol: "NBL.NYSE", stock: "Noble Energy, Inc." },
  { Symbol: "NEE.NYSE", stock: "NextEra Energy, Inc." },
  { Symbol: "NEM.NYSE", stock: "Newmont Corporation" },
  { Symbol: "NFLX.NYSE", stock: "Netflix, Inc." },
  { Symbol: "NI.NYSE", stock: "NiSource, Inc." },
  { Symbol: "NKE.NYSE", stock: "Nike, Inc." },
  { Symbol: "NLOK.NYSE", stock: "NortonLifeLock, Inc." },
  { Symbol: "NOK.NYSE", stock: "Nokia Corporation" },
  { Symbol: "NTR.NYSE", stock: "Nutrien Ltd." },
  { Symbol: "NVDA.NYSE", stock: "NVIDIA Corporation" },
  { Symbol: "NWL.NYSE", stock: "Newell Brands, Inc." },
  { Symbol: "NXPI.NYSE", stock: "NXP Semiconductors N.V." },
  { Symbol: "O.NYSE", stock: "Realty Income Corporation" },
  { Symbol: "OKE.NYSE", stock: "ONEOK, Inc." },
  { Symbol: "OMC.NYSE", stock: "Omnicom Group Inc." },
  { Symbol: "ORCL.NYSE", stock: "Oracle Corporation" },
  { Symbol: "OXY.NYSE", stock: "Occidental Petroleum Corporation" },
  { Symbol: "P.NYSE", stock: "Pandora Media, Inc." },
  { Symbol: "PFE.NYSE", stock: "Pfizer Inc." },
  { Symbol: "PG.NYSE", stock: "Procter & Gamble Company" },
  { Symbol: "PM.NYSE", stock: "Philip Morris International Inc." },
  { Symbol: "PNC.NYSE", stock: "PNC Financial Services Group, Inc." },
  { Symbol: "POOL.NYSE", stock: "Pool Corporation" },
  { Symbol: "PPG.NYSE", stock: "PPG Industries, Inc." },
  { Symbol: "PRGO.NYSE", stock: "Perrigo Company" },
  { Symbol: "PSA.NYSE", stock: "Public Storage" },
  { Symbol: "PSX.NYSE", stock: "Phillips 66" },
  { Symbol: "PXD.NYSE", stock: "Pioneer Natural Resources Company" },
  { Symbol: "QCOM.NYSE", stock: "Qualcomm Incorporated" },
  { Symbol: "R.NYSE", stock: "Raytheon Technologies Corporation" },
  { Symbol: "REG.NYSE", stock: "Regency Centers Corporation" },
  { Symbol: "RF.NYSE", stock: "Regions Financial Corporation" },
  { Symbol: "RGA.NYSE", stock: "Reinsurance Group of America" },
  { Symbol: "RHI.NYSE", stock: "Robert Half International, Inc." },
  { Symbol: "RKT.NYSE", stock: "Rocket Companies, Inc." },
  { Symbol: "RL.NYSE", stock: "Ralph Lauren Corporation" },
  { Symbol: "RMD.NYSE", stock: "ResMed Inc." },
  { Symbol: "ROK.NYSE", stock: "Rockwell Automation, Inc." },
  { Symbol: "ROP.NYSE", stock: "Roper Technologies, Inc." },
  { Symbol: "ROST.NYSE", stock: "Ross Stores, Inc." },
  { Symbol: "RSG.NYSE", stock: "Republic Services, Inc." },
  { Symbol: "S.NYSE", stock: "Sprint Corporation" },
  { Symbol: "SBUX.NYSE", stock: "Starbucks Corporation" },
  { Symbol: "SCG.NYSE", stock: "SCANA Corporation" },
  { Symbol: "SCHW.NYSE", stock: "Charles Schwab Corporation" },
  { Symbol: "SEE.NYSE", stock: "Sealed Air Corporation" },
  { Symbol: "SHW.NYSE", stock: "Sherwin-Williams Company" },
  { Symbol: "SIVB.NYSE", stock: "Silicon Valley Bank" },
  { Symbol: "SKT.NYSE", stock: "Tanger Factory Outlet Centers, Inc." },
  { Symbol: "SLB.NYSE", stock: "Schlumberger N.V." },
  { Symbol: "SNA.NYSE", stock: "Snap-on Incorporated" },
  { Symbol: "SO.NYSE", stock: "Southern Company" },
  { Symbol: "SPG.NYSE", stock: "Simon Property Group, Inc." },
  { Symbol: "SPGI.NYSE", stock: "S&P Global Inc." },
  { Symbol: "SPLK.NYSE", stock: "Splunk Inc." },
  { Symbol: "SPWR.NYSE", stock: "SunPower Corporation" },
  { Symbol: "STT.NYSE", stock: "State Street Corporation" },
  { Symbol: "STZ.NYSE", stock: "Constellation Brands, Inc." },
  { Symbol: "SUI.NYSE", stock: "Sun Communities, Inc." },
  { Symbol: "SWK.NYSE", stock: "Stanley Black & Decker, Inc." },
  { Symbol: "SWKS.NYSE", stock: "Skyworks Solutions, Inc." },
  { Symbol: "SYF.NYSE", stock: "Synchrony Financial" },
  { Symbol: "SYK.NYSE", stock: "Stryker Corporation" },
  { Symbol: "T.NYSE", stock: "AT&T Inc." },
  { Symbol: "TAP.NYSE", stock: "Molson Coors Beverage Company" },
  { Symbol: "TGT.NYSE", stock: "Target Corporation" },
  { Symbol: "TMO.NYSE", stock: "Thermo Fisher Scientific, Inc." },
  { Symbol: "TMUS.NYSE", stock: "T-Mobile US, Inc." },
  { Symbol: "TRV.NYSE", stock: "The Travelers Companies, Inc." },
  { Symbol: "TSCO.NYSE", stock: "Tractor Supply Company" },
  { Symbol: "TSLA.NYSE", stock: "Tesla, Inc." },
  { Symbol: "TSS.NYSE", stock: "Total System Services, Inc." },
  { Symbol: "TWTR.NYSE", stock: "Twitter, Inc." },
  { Symbol: "TXN.NYSE", stock: "Texas Instruments, Inc." },
  { Symbol: "UNH.NYSE", stock: "UnitedHealth Group Incorporated" },
  { Symbol: "UPS.NYSE", stock: "United Parcel Service, Inc." },
  { Symbol: "USB.NYSE", stock: "U.S. Bancorp" },
  { Symbol: "V.NYSE", stock: "Visa Inc." },
  { Symbol: "VFC.NYSE", stock: "VF Corporation" },
  { Symbol: "VLO.NYSE", stock: "Valero Energy Corporation" },
  { Symbol: "VZ.NYSE", stock: "Verizon Communications Inc." },
  { Symbol: "WBA.NYSE", stock: "Walgreens Boots Alliance, Inc." },
  { Symbol: "WDC.NYSE", stock: "Western Digital Corporation" },
  { Symbol: "WMT.NYSE", stock: "Walmart Inc." },
  { Symbol: "WU.NYSE", stock: "Western Union Company" },
  { Symbol: "WY.NYSE", stock: "Weyerhaeuser Company" },
  { Symbol: "XOM.NYSE", stock: "Exxon Mobil Corporation" },
  { Symbol: "YUM.NYSE", stock: "Yum! Brands, Inc." },
];

export const NASDAQ_Stocks = [
  { Symbol: "AAL.NAS", stock: "American Airlines Group" },
  { Symbol: "AAPL.NAS", stock: "Apple Inc CFD" },
  { Symbol: "AAXJ.NAS", stock: "iShares MSCI All Country Asia ex Japan ETF" },
  { Symbol: "ABCB.NAS", stock: "Ameris Bancorp" },
  { Symbol: "ABEO.NAS", stock: "Abeona Therapeutics Inc." },
  { Symbol: "ABMD.NAS", stock: "ABIOMED Inc" },
  { Symbol: "ABNB.NAS", stock: "Airbnb Inc. Class A Common Stock" },
  { Symbol: "ABUS.NAS", stock: "Arbutus Biopharma" },
  { Symbol: "ACAD.NAS", stock: "ACADIA Pharmaceuticals Inc" },
  { Symbol: "ACLS.NAS", stock: "Axcelis Technologies Inc" },
  { Symbol: "ACMR.NAS", stock: "ACM Research Inc" },
  { Symbol: "ACRX.NAS", stock: "AcelRx Pharmaceuticals Inc" },
  { Symbol: "ACWI.NAS", stock: "iShares MSCI ACWI ETF" },
  { Symbol: "ADAG.NAS", stock: "Adagene Inc ADR" },
  { Symbol: "ADAP.NAS", stock: "Adaptimmune Therapeutics PLC" },
  { Symbol: "ADBE.NAS", stock: "Adobe Systems CFD" },
  { Symbol: "ADES.NAS", stock: "Advanced Emissions Solutions Inc" },
  { Symbol: "ADGI.NAS", stock: "Adagio Therapeutics Inc." },
  { Symbol: "ADI.NAS", stock: "Analog Devices CFD" },
  { Symbol: "ADMP.NAS", stock: "Adamis Pharmaceuticals Corp" },
  { Symbol: "ADN.NAS", stock: "Advent Technologies Holdings Inc" },
  { Symbol: "ADP.NAS", stock: "Automatic Data Processing (ADP) CFD" },
  { Symbol: "ADPT.NAS", stock: "Adaptive Biotechnologies" },
  { Symbol: "ADSK.NAS", stock: "Autodesk Inc." },
  { Symbol: "ADTH.NAS", stock: "AdTheorent Holding Company Inc" },
  { Symbol: "ADUS.NAS", stock: "Addus Homecare Corp" },
  { Symbol: "ADV.NAS", stock: "Advantage Solutions Inc" },
  { Symbol: "ADVM.NAS", stock: "Adverum Biotechnologies Inc" },
  { Symbol: "AEHR.NAS", stock: "Aehr Test Systems" },
  { Symbol: "AEP.NAS", stock: "American Electric Power" },
  { Symbol: "AFMD.NAS", stock: "Affimed N.V." },
  { Symbol: "AFRM.NAS", stock: "Affirm Holdings Inc. Class A Common Stock" },
  { Symbol: "AFYA.NAS", stock: "Afya Ltd" },
  { Symbol: "AGEN.NAS", stock: "Agenus Inc" },
  { Symbol: "AGLE.NAS", stock: "Aeglea BioTherapeutics, Inc." },
  { Symbol: "AGNC.NAS", stock: "AGNC Investment Corp" },
  { Symbol: "AGRX.NAS", stock: "Agile Therapeutics Inc" },
  { Symbol: "AHCO.NAS", stock: "Adapthealth Corp" },
  { Symbol: "AHG.NAS", stock: "Akso Health Group" },
  { Symbol: "AIKI.NAS", stock: "Aikido Pharma Inc" },
  { Symbol: "AINV.NAS", stock: "Apollo Investment Corp" },
  { Symbol: "AIRG.NAS", stock: "Airgain Inc" },
  { Symbol: "AIRS.NAS", stock: "AirSculpt Technologies Inc." },
  { Symbol: "AKAM.NAS", stock: "Akamai Technologies Inc" },
  { Symbol: "AKRO.NAS", stock: "Akero Therapeutics Inc" },
  { Symbol: "AKTS.NAS", stock: "Akoustis Technologies Inc" },
  { Symbol: "AKTX.NAS", stock: "Akari Therapeutics PLC" },
  { Symbol: "AKUS.NAS", stock: "Akouos Inc" },
  { Symbol: "AKYA.NAS", stock: "Akoya Biosciences, Inc." },
  { Symbol: "ALBO.NAS", stock: "Albireo Pharma, Inc" },
  { Symbol: "ALDX.NAS", stock: "Aldeyra Therapeutics Inc" },
  { Symbol: "ALEC.NAS", stock: "Alector Inc" },
  { Symbol: "ALGN.NAS", stock: "Align Technology" },
  { Symbol: "ALNY.NAS", stock: "Alnylam Pharmaceuticals Inc. Common Stock" },
  { Symbol: "ALPN.NAS", stock: "Alpine Immune Sciences Inc" },
  { Symbol: "ALRM.NAS", stock: "Alarm.com Holdings Inc" },
  { Symbol: "ALRN.NAS", stock: "Aileron Therapeutics Inc" },
  { Symbol: "ALRS.NAS", stock: "Werner Enterprises Inc" },
  { Symbol: "ALT.NAS", stock: "Altimmune Inc" },
  { Symbol: "ALVR.NAS", stock: "Allovir Inc" },
  { Symbol: "ALXN.NAS", stock: "Alexion Pharmaceuticals" },
  { Symbol: "AMAT.NAS", stock: "Applied Materials CFD" },
  { Symbol: "AMBA.NAS", stock: "Ambarella Inc" },
  { Symbol: "AMD.NAS", stock: "Advanced Micro Devices Inc" },
  { Symbol: "AMED.NAS", stock: "Amedisys Inc Common Stock" },
  { Symbol: "AMGN.NAS", stock: "Amgen CFD" },
  { Symbol: "AMRS.NAS", stock: "Amyris Inc" },
  { Symbol: "AMTX.NAS", stock: "Aemetis Inc" },
  { Symbol: "AMZN.NAS", stock: "Amazon.com CFD" },
  { Symbol: "ANDE.NAS", stock: "Andersons Inc/The" },
  { Symbol: "ANGI.NAS", stock: "ANGI Homeservices Inc" },
  { Symbol: "ANSS.NAS", stock: "ANSYS, Inc." },
  { Symbol: "ANTE.NAS", stock: "Airnet Technology Inc" },
  { Symbol: "APA.NAS", stock: "Apache Corporation" },
  { Symbol: "APHA.NAS", stock: "Aphria Inc" },
  { Symbol: "APPF.NAS", stock: "AppFolio Inc" },
  { Symbol: "APPN.NAS", stock: "Appian Corporation Class A Common Stock" },
  { Symbol: "ARAY.NAS", stock: "Accuray Inc" },
  { Symbol: "ARCC.NAS", stock: "Ares Capital Corp" },
  { Symbol: "ARCT.NAS", stock: "Arcturus Therapeutics Holdings Inc" },
  { Symbol: "ARWR.NAS", stock: "Arrowhead Research Corp" },
  { Symbol: "ASTE.NAS", stock: "Astec Industries Inc" },
  { Symbol: "ATEC.NAS", stock: "Alphatec Holdings Inc" },
  { Symbol: "ATHX.NAS", stock: "Athersys Inc" },
  { Symbol: "ATNX.NAS", stock: "Athenex Inc" },
  { Symbol: "ATRA.NAS", stock: "Atara Biotherapeutics Inc" },
  { Symbol: "ATRS.NAS", stock: "Antares Pharma Inc" },
  { Symbol: "ATSG.NAS", stock: "Air Transport Services Group Inc" },
  { Symbol: "ATVI.NAS", stock: "Activision Blizzard CFD" },
  { Symbol: "AVAV.NAS", stock: "Aerovironment Inc" },
  { Symbol: "AVGO.NAS", stock: "Broadcom Ltd CFD" },
  { Symbol: "AVID.NAS", stock: "Avid Technology Inc" },
  { Symbol: "AVT.NAS", stock: "Avnet Inc" },
  { Symbol: "AVXL.NAS", stock: "Anavex Life Sciences Corp" },
  { Symbol: "AXGN.NAS", stock: "AxoGen Inc" },
  { Symbol: "AXON.NAS", stock: "Axon Enterprise Inc" },
  { Symbol: "AXSM.NAS", stock: "Axsome Therapeutics Inc" },
  { Symbol: "AY.NAS", stock: "Atlantica Yield PLC" },
  { Symbol: "AYRO.NAS", stock: "AYRO Inc" },
  { Symbol: "AYTU.NAS", stock: "Aytu BioScience Inc" },
  { Symbol: "AZN.NAS", stock: "AstraZeneca (US)" },
  { Symbol: "AZPN.NAS", stock: "Aspen Technology Inc. Common Stock" },
  { Symbol: "BBBY.NAS", stock: "Bed Bath & Beyond" },
  { Symbol: "BBIG.NAS", stock: "Vinco Ventures Inc" },
  { Symbol: "BBIO.NAS", stock: "BridgeBio Pharma" },
];

export const EURONEXT = [
  { Symbol: "AALB.AMS", stock: "Aalberts Inds" },
  { Symbol: "ABN.AMS", stock: "ABN AMRO Group" },
  { Symbol: "AD.AMS", stock: "Koninklijke Ahold Delhaize NV" },
  { Symbol: "AGN.AMS", stock: "Aegon" },
  { Symbol: "AKZA.AMS", stock: "Akzo Nobel NV" },
  { Symbol: "ASML.AMS", stock: "ASML" },
  { Symbol: "ASRNL.AMS", stock: "ASR Nederland NV" },
  { Symbol: "DSM.AMS", stock: "DSM" },
  { Symbol: "ECMPA.AMS", stock: "Eurocommercial Properties" },
  { Symbol: "FUR.AMS", stock: "Fugro NV" },
  { Symbol: "GLPG.AMS", stock: "Galapagos NV" },
  { Symbol: "HEIA.AMS", stock: "Heineken" },
  { Symbol: "INGA.AMS", stock: "ING Groep NV (NL)" },
  { Symbol: "KPN.AMS", stock: "KPN" },
  { Symbol: "NN.AMS", stock: "NN Group NV" },
  { Symbol: "PHIA.AMS", stock: "Kon Philips" },
  { Symbol: "RAND.AMS", stock: "Randstad" },
  { Symbol: "SBMO.AMS", stock: "SBM Offshore" },
  { Symbol: "TOM2.AMS", stock: "TomTom" },
  { Symbol: "UNA.AMS", stock: "Unilever PLC - ADR" },
  { Symbol: "URW.AMS", stock: "Unibail Rodamco SE & WFD" },
  { Symbol: "VPK.AMS", stock: "Vopak" },
  { Symbol: "WHA.AMS", stock: "Wereldhave" },
  { Symbol: "WKL.AMS", stock: "Wolters Kluwer" },
];

export const Xetra = [
  { Symbol: "1COV.ETR", stock: "Covestro AG" },
  { Symbol: "ADS.ETR", stock: "Adidas AG" },
  { Symbol: "ADV.ETR", stock: "Adva" },
  { Symbol: "AFX.ETR", stock: "Carl Zeiss Meditec" },
  { Symbol: "AIXA.ETR", stock: "Aixtron" },
  { Symbol: "ALV.ETR", stock: "Allianz SE (DE)" },
  { Symbol: "ARL.ETR", stock: "Aareal Bank" },
  { Symbol: "BAS.ETR", stock: "Basf Se (DE)" },
  { Symbol: "BAYN.ETR", stock: "Bayer AG (DE)" },
  { Symbol: "BC8.ETR", stock: "Bechtle" },
  { Symbol: "BEI.ETR", stock: "Beiersdorf" },
  { Symbol: "BMW.ETR", stock: "Bayerische Motoren Werke AG (Preference)" },
  { Symbol: "BNR.ETR", stock: "Brenntag SE" },
  { Symbol: "BOSS.ETR", stock: "Hugo Boss" },
  { Symbol: "CBK.ETR", stock: "Commerzbank AG (DE)" },
  { Symbol: "COK.ETR", stock: "Cancom SE" },
  { Symbol: "CON.ETR", stock: "Continental AG" },
  { Symbol: "COP.ETR", stock: "CompuGroup Medical SE & Co KGaA" },
  { Symbol: "DB1.ETR", stock: "Deutsche Boerse NA" },
  { Symbol: "DBK.ETR", stock: "Deutsche Bank AG (DE)" },
  { Symbol: "DEZ.ETR", stock: "Deutz" },
  { Symbol: "DPW.ETR", stock: "Deutsche Post AG" },
  { Symbol: "DRI.ETR", stock: "1&1 AG" },
  { Symbol: "DRW8.ETR", stock: "Draegerwerk AG & Co KGaA" },
  { Symbol: "DTE.ETR", stock: "Deutsche Telekom AG (DE)" },
  { Symbol: "DWNI.ETR", stock: "Deutsche Wohnen SE" },
  { Symbol: "EOAN.ETR", stock: "E.On Se (DE)" },
  { Symbol: "EVK.ETR", stock: "Evonik Industries AG" },
  { Symbol: "EVT.ETR", stock: "Evotec" },
  { Symbol: "FME.ETR", stock: "Fresenius Medical Care AG (DE)" },
  { Symbol: "FNTN.ETR", stock: "Freenet" },
  { Symbol: "FPE3.ETR", stock: "Fuchs Petrolub AG" },
  { Symbol: "FRA.ETR", stock: "Fraport" },
  { Symbol: "FRE.ETR", stock: "Fresenius KGaA" },
  { Symbol: "G1A.ETR", stock: "GEA" },
  { Symbol: "GBF.ETR", stock: "Bilfinger Berger" },
  { Symbol: "GFT.ETR", stock: "GFT Technologies AG" },
  { Symbol: "HEI.ETR", stock: "HeidelbergCement AG" },
  { Symbol: "HEN3.ETR", stock: "Henkel AG & Co KGaA" },
  { Symbol: "HNR1.ETR", stock: "Hannover RE" },
  { Symbol: "HOT.ETR", stock: "HOCHTIEF" },
  { Symbol: "IFX.ETR", stock: "Infineon TECH.AG" },
  { Symbol: "KCO.ETR", stock: "Kloeckner & Co" },
  { Symbol: "KGX.ETR", stock: "KION Group AG" },
  { Symbol: "KRN.ETR", stock: "Krones" },
  { Symbol: "LEO.ETR", stock: "Leoni" },
  { Symbol: "LHA.ETR", stock: "Lufthansa" },
  { Symbol: "LIN.ETR", stock: "Linde Plc (DE)" },
  { Symbol: "LXS.ETR", stock: "Lanxess" },
  { Symbol: "M5Z.ETR", stock: "Manz Automation" },
  { Symbol: "MOR.ETR", stock: "Morphosys" },
  { Symbol: "MRK.ETR", stock: "Merck KGAA" },
  { Symbol: "MTX.ETR", stock: "MTU Aero Engines NA" },
  { Symbol: "MUV2.ETR", stock: "Muench.Rueckvers.VNA" },
  { Symbol: "NDA.ETR", stock: "Aurubis" },
  { Symbol: "NDX1.ETR", stock: "Nordex" },
  { Symbol: "NEM.ETR", stock: "Nemetschek AG" },
  { Symbol: "NWO.ETR", stock: "New Work SE" },
  { Symbol: "O2D.ETR", stock: "Telefonica Deutschland Holding" },
  { Symbol: "P911.ETR", stock: "Porsche AG" },
  { Symbol: "PAH3.ETR", stock: "Porsche Automobil Holding" },
  { Symbol: "PFV.ETR", stock: "Pfeiffer Vacuum" },
  { Symbol: "PSM.ETR", stock: "ProSiebenSat 1" },
  { Symbol: "QIA.ETR", stock: "Qiagen N.V." },
  { Symbol: "RHK.ETR", stock: "Rhoen-Klinikum" },
  { Symbol: "RHM.ETR", stock: "Rheinmetall" },
  { Symbol: "RRTL.ETR", stock: "RTL Group SA (DE)" },
  { Symbol: "RWE.ETR", stock: "RWE AG (DE)" },
  { Symbol: "SAP.ETR", stock: "SAP SE" },
  { Symbol: "SDF.ETR", stock: "K+S" },
  { Symbol: "SGL.ETR", stock: "SGL" },
  { Symbol: "SHA.ETR", stock: "Schaeffler AG" },
  { Symbol: "SIE.ETR", stock: "Siemens AG (DE)" },
  { Symbol: "SMHN.ETR", stock: "Suess Microtec" },
  { Symbol: "SOW.ETR", stock: "Software" },
  { Symbol: "SRT.ETR", stock: "Sartorius AG Vz" },
  { Symbol: "SY1.ETR", stock: "Symrise AG" },
  { Symbol: "SZG.ETR", stock: "Salzgitter" },
  { Symbol: "SZU.ETR", stock: "Suedzucker" },
  { Symbol: "TEG.ETR", stock: "TAG Immobilien AG" },
  { Symbol: "TKA.ETR", stock: "ThyssenKrupp" },
  { Symbol: "TLX.ETR", stock: "Talanx AG" },
  { Symbol: "UN01.ETR", stock: "Uniper AG" },
  { Symbol: "UTDI.ETR", stock: "United Internet" },
  { Symbol: "VNA.ETR", stock: "Vonovia SE" },
  { Symbol: "VOW3.ETR", stock: "Volkswagen AG" },
  { Symbol: "WAF.ETR", stock: "Siltronic AG" },
  { Symbol: "WCH.ETR", stock: "Wacker Chemie" },
  { Symbol: "ZAL.ETR", stock: "Zalando SE" },
  { Symbol: "ZIL2.ETR", stock: "ElringKlinger" },
];

export const London_Stock_Exchange = [
  { Symbol: "AAL.LSE", stock: "Anglo American" },
  { Symbol: "ABF.LSE", stock: "Associated British Foods" },
  { Symbol: "ADM.LSE", stock: "Admiral Group" },
  { Symbol: "AHT.LSE", stock: "Ashtead Group" },
  { Symbol: "AML.LSE", stock: "Aston Martin Lagonda Global Holdings PLC" },
  { Symbol: "ANTO.LSE", stock: "Antofagasta" },
  { Symbol: "ATST.LSE", stock: "Alliance Trust" },
  { Symbol: "AUTO.LSE", stock: "Auto Trader Group PLC" },
  { Symbol: "AV.LSE", stock: "Aviva" },
  { Symbol: "AZN.LSE", stock: "AstraZeneca" },
  { Symbol: "BA.LSE", stock: "BAE Systems" },
  { Symbol: "BARC.LSE", stock: "Barclays" },
  { Symbol: "BATS.LSE", stock: "British American Tobacco PLC (GB)" },
  { Symbol: "BDEV.LSE", stock: "Barratt Developments" },
  { Symbol: "BHP.LSE", stock: "BHP Group PLC (GB)" },
  { Symbol: "BKG.LSE", stock: "Berkeley Group" },
  { Symbol: "BLND.LSE", stock: "British Land" },
  { Symbol: "BNZL.LSE", stock: "Bunzl" },
  { Symbol: "BP.LSE", stock: "BP" },
  { Symbol: "BRBY.LSE", stock: "Burberry Group" },
  { Symbol: "BTA.LSE", stock: "BT Group" },
  { Symbol: "CCH.LSE", stock: "Coca-Cola HBC AG" },
  { Symbol: "CCL.LSE", stock: "Carnival" },
  { Symbol: "CNA.LSE", stock: "Centrica" },
  { Symbol: "CPG.LSE", stock: "Compass Group" },
  { Symbol: "CPI.LSE", stock: "Capita Group" },
  { Symbol: "CRH.LSE", stock: "CRH (UK)" },
  { Symbol: "DCC.LSE", stock: "Dcc PLC (GB)" },
  { Symbol: "DGE.LSE", stock: "Diageo PLC (GB)" },
  { Symbol: "DLG.LSE", stock: "Direct Line Insurance Group" },
  { Symbol: "EMG.LSE", stock: "Man Group PLC" },
  { Symbol: "EXPN.LSE", stock: "Experian" },
  { Symbol: "EZJ.LSE", stock: "EasyJet" },
  { Symbol: "FLTR.LSE", stock: "Flutter Entertainment" },
  { Symbol: "FRES.LSE", stock: "Fresnillo" },
  { Symbol: "GLEN.LSE", stock: "Glencore Xstrata plc (UK)" },
  { Symbol: "GSK.LSE", stock: "GlaxoSmithKline" },
  { Symbol: "HAS.LSE", stock: "Hays" },
  { Symbol: "HL.LSE", stock: "Hargreaves Lansdown" },
  { Symbol: "HLMA.LSE", stock: "Halma" },
  { Symbol: "HMSO.LSE", stock: "Hammerson" },
  { Symbol: "HSBA.LSE", stock: "HSBC" },
  { Symbol: "IAG.LSE", stock: "International Consolidated Airlines Group" },
  { Symbol: "ICP.LSE", stock: "Intermediate Cap" },
  { Symbol: "III.LSE", stock: "3i Group" },
  { Symbol: "IMB.LSE", stock: "Imperial Brands" },
  { Symbol: "IMI.LSE", stock: "IMI" },
  { Symbol: "INF.LSE", stock: "Informa" },
  { Symbol: "ITRK.LSE", stock: "Intertek Group" },
  { Symbol: "ITV.LSE", stock: "ITV" },
  { Symbol: "JE.LSE", stock: "Just Eat Plc" },
  { Symbol: "JMAT.LSE", stock: "Johnson Matthey" },
  { Symbol: "JUP.LSE", stock: "Jupiter Fund Management PLC" },
  { Symbol: "KGF.LSE", stock: "Kingfisher" },
  { Symbol: "LAND.LSE", stock: "Land Securities" },
  { Symbol: "LGEN.LSE", stock: "Legal & General" },
  { Symbol: "LLOY.LSE", stock: "Lloyds Banking" },
  { Symbol: "LSE.LSE", stock: "London Stock Exchange" },
  { Symbol: "MGGT.LSE", stock: "Meggitt" },
  { Symbol: "MKS.LSE", stock: "Marks & Spencer" },
  { Symbol: "MNDI.LSE", stock: "Mondi" },
  { Symbol: "MRO.LSE", stock: "Melrose" },
  { Symbol: "NEX.LSE", stock: "National Express" },
  { Symbol: "NG.LSE", stock: "National Grid" },
  { Symbol: "NXT.LSE", stock: "Next" },
  { Symbol: "OCDO.LSE", stock: "Ocado Group" },
  { Symbol: "OMU.LSE", stock: "Old Mutual" },
  { Symbol: "PFC.LSE", stock: "Petrofac" },
  { Symbol: "PRU.LSE", stock: "Prudential" },
  { Symbol: "PSN.LSE", stock: "Persimmon" },
  { Symbol: "PSON.LSE", stock: "Pearson" },
  { Symbol: "RB.LSE", stock: "Reckitt Benckiser" },
  { Symbol: "RDSB.LSE", stock: "Shell PLC (GB)" },
  { Symbol: "REL.LSE", stock: "RELX PLC" },
  { Symbol: "RIO.LSE", stock: "Rio Tinto PLC" },
  { Symbol: "RMG.LSE", stock: "Royal Mail Group" },
  { Symbol: "RR.LSE", stock: "Rolls-Royce" },
  { Symbol: "RTO.LSE", stock: "Rentokil Initial" },
  { Symbol: "SBRY.LSE", stock: "Sainsbury" },
  { Symbol: "SDR.LSE", stock: "Schroders" },
  { Symbol: "SGE.LSE", stock: "Sage Group" },
  { Symbol: "SGRO.LSE", stock: "SEGRO" },
  { Symbol: "SKG.LSE", stock: "Smurfit Kappa Group PLC GB" },
  { Symbol: "SMDS.LSE", stock: "DS Smith" },
  { Symbol: "SMIN.LSE", stock: "Smiths Group" },
  { Symbol: "SMT.LSE", stock: "Scottish Mortgage IT" },
  { Symbol: "SN.LSE", stock: "Smith & Nephew" },
  { Symbol: "SRP.LSE", stock: "Serco Group" },
  { Symbol: "STAN.LSE", stock: "Standard Chartered" },
  { Symbol: "STJ.LSE", stock: "St James's Place" },
  { Symbol: "SVT.LSE", stock: "Severn Trent" },
  { Symbol: "TED.LSE", stock: "Ted Baker" },
  { Symbol: "TLW.LSE", stock: "Tullow Oil PLC (GB)" },
  { Symbol: "TPK.LSE", stock: "Travis Perkins" },
  { Symbol: "TSCO.LSE", stock: "Tesco" },
  { Symbol: "TUI.LSE", stock: "TUI AG (GB)" },
  { Symbol: "ULVR.LSE", stock: "Unilever PLC" },
  { Symbol: "UU.LSE", stock: "United Utilities" },
  { Symbol: "VOD.LSE", stock: "Vodafone" },
  { Symbol: "WPP.LSE", stock: "WPP" },
  { Symbol: "WTB.LSE", stock: "Whitbread" },
];

export const Euronext = [
  { Symbol: "AC.PAR", stock: "Accor" },
  { Symbol: "ACA.PAR", stock: "Credit Agricole" },
  { Symbol: "AF.PAR", stock: "AIR France-KLM" },
  { Symbol: "AI.PAR", stock: "Air Liquide" },
  { Symbol: "AIR.PAR", stock: "Airbus SE" },
  { Symbol: "AKE.PAR", stock: "Arkema" },
  { Symbol: "ALD.PAR", stock: "ALD SA" },
  { Symbol: "ALO.PAR", stock: "Alstom" },
  { Symbol: "ATO.PAR", stock: "Atos Origin" },
  { Symbol: "BN.PAR", stock: "Danone" },
  { Symbol: "BNP.PAR", stock: "BNP Paribas SA (FR)" },
  { Symbol: "BOL.PAR", stock: "Bollore" },
  { Symbol: "BVI.PAR", stock: "Bureau Veritas" },
  { Symbol: "CA.PAR", stock: "Carrefour" },
  { Symbol: "CAP.PAR", stock: "Cap Gemini" },
  { Symbol: "CDI.PAR", stock: "Christian Dior SA" },
  { Symbol: "CO.PAR", stock: "Casino Guichard Perrachon" },
  { Symbol: "CS.PAR", stock: "AXA SA (FR)" },
  { Symbol: "DG.PAR", stock: "Vinci" },
  { Symbol: "DSY.PAR", stock: "Dassault Systemes" },
  { Symbol: "EDEN.PAR", stock: "Edenred" },
  { Symbol: "EDF.PAR", stock: "Electricite de France SA" },
  { Symbol: "EL.PAR", stock: "Essilor International" },
  { Symbol: "EN.PAR", stock: "Bouygues" },
  { Symbol: "ENGI.PAR", stock: "Engie" },
  { Symbol: "EO.PAR", stock: "Faurecia" },
  { Symbol: "FGR.PAR", stock: "Eiffage" },
  { Symbol: "FNAC.PAR", stock: "Fnac Darty" },
  { Symbol: "FP.PAR", stock: "TotalEnergies (FR)" },
  { Symbol: "FR.PAR", stock: "Valeo" },
  { Symbol: "GLE.PAR", stock: "Société Générale" },
  { Symbol: "HO.PAR", stock: "Thales" },
  { Symbol: "ICAD.PAR", stock: "Icade" },
  { Symbol: "JCDX.PAR", stock: "JCDecaux" },
  { Symbol: "KER.PAR", stock: "Kering" },
  { Symbol: "LR.PAR", stock: "Legrand" },
  { Symbol: "MAU.PAR", stock: "Maurel & Prom" },
  { Symbol: "MC.PAR", stock: "LVMH Moet Hennessy Louis Vuitton SA (FR)" },
  { Symbol: "ML.PAR", stock: "Michelin" },
  { Symbol: "MMB.PAR", stock: "Lagardere" },
  { Symbol: "OR.PAR", stock: "L'Oreal" },
  { Symbol: "ORA.PAR", stock: "Orange" },
  { Symbol: "POM.PAR", stock: "Plastic Omnium" },
  { Symbol: "PUB.PAR", stock: "Publicis Groupe" },
  { Symbol: "RCO.PAR", stock: "Remy Cointreau" },
  { Symbol: "RI.PAR", stock: "Pernod Ricard" },
  { Symbol: "RMS.PAR", stock: "Hermes" },
  { Symbol: "RNO.PAR", stock: "Renault SA (FR)" },
  { Symbol: "SAF.PAR", stock: "Safran" },
  { Symbol: "SAN.PAR", stock: "Sanofi (FR)" },
  { Symbol: "SGO.PAR", stock: "Saint Gobain" },
  { Symbol: "SU.PAR", stock: "Schneider Electric" },
  { Symbol: "SW.PAR", stock: "Sodexo" },
  { Symbol: "TCH.PAR", stock: "Technicolor" },
  { Symbol: "UBI.PAR", stock: "Ubisoft Entertainment" },
  { Symbol: "UG.PAR", stock: "Peugeot Invest" },
  { Symbol: "VCT.PAR", stock: "Vicat" },
  { Symbol: "VIE.PAR", stock: "Veolia Environment" },
  { Symbol: "VIV.PAR", stock: "Vivendi" },
  { Symbol: "VK.PAR", stock: "Vallourec" },
];

export const Bolsa = [
  { Symbol: "ACS.MAD", stock: "ACS" },
  { Symbol: "ACX.MAD", stock: "Acerinox SA" },
  { Symbol: "AENA.MAD", stock: "Aena SA" },
  { Symbol: "AMS.MAD", stock: "Amadeus IT Holdings SA" },
  { Symbol: "ANA.MAD", stock: "Acciona" },
  { Symbol: "BBVA.MAD", stock: "BBVA SA (ES)" },
  { Symbol: "BKT.MAD", stock: "BankInter" },
  { Symbol: "CABK.MAD", stock: "CaixaBank SA" },
  { Symbol: "CIE.MAD", stock: "CIE Automotive" },
  { Symbol: "CLNX.MAD", stock: "Cellnex" },
  { Symbol: "COL.MAD", stock: "Inmobiliaria Colonial" },
  { Symbol: "ELE.MAD", stock: "Endesa" },
  { Symbol: "ENG.MAD", stock: "Enagas" },
  { Symbol: "FER.MAD", stock: "Ferrovial" },
  { Symbol: "GRF.MAD", stock: "Grifols SA" },
  { Symbol: "IBE.MAD", stock: "Iberdrola" },
  { Symbol: "IDR.MAD", stock: "Indra Sistemas" },
  { Symbol: "ITX.MAD", stock: "Inditex" },
  { Symbol: "MAP.MAD", stock: "Mapfre" },
  { Symbol: "MEL.MAD", stock: "Melia Hotels International" },
  { Symbol: "MRL.MAD", stock: "Merlin Properties Socimi SA" },
  { Symbol: "MTS.MAD", stock: "ArcelorMittal (ES)" },
  { Symbol: "NTGY.MAD", stock: "Naturgy Energy Group" },
  { Symbol: "REP.MAD", stock: "Repsol YPF" },
  { Symbol: "SAB.MAD", stock: "Banco de Sabadell" },
  { Symbol: "SAN.MAD", stock: "Banco Santander SA (ES)" },
  { Symbol: "SGRE.MAD", stock: "Siemens Gamesa Renewable Energy" },
  { Symbol: "TEF.MAD", stock: "Telefonica SA (ES)" },
  { Symbol: "TL5.MAD", stock: "Mediaset Espana Comunicacion SA" },
  { Symbol: "TRE.MAD", stock: "Tecnicas Reunida" },
];

export const ASX = [
  {
    Symbol: "AMC.ASX",
    stock: "Amcor CFD",
  },
  {
    Symbol: "AMP.ASX",
    stock: "AMP (AUD) CFD",
  },
  {
    Symbol: "ANZ.ASX",
    stock: "Australia and NZ Banking Group Ltd (AUD) CFD",
  },
  {
    Symbol: "BHP.ASX",
    stock: "BHP Billiton (AUD) CFD",
  },
  {
    Symbol: "BXB.ASX",
    stock: "Brambles Ltd CFD",
  },
  {
    Symbol: "CBA.ASX",
    stock: "Commonwealth Bank of Australia CFD",
  },
  {
    Symbol: "CSL.ASX",
    stock: "CSL Ltd CFD",
  },
  {
    Symbol: "FMG.ASX",
    stock: "Fortescue Metals Group CFD",
  },
  {
    Symbol: "IAG.ASX",
    stock: "Insurance Australia Group CFD",
  },
  {
    Symbol: "MQG.ASX",
    stock: "Macquarie Group Ltd CFD",
  },
  {
    Symbol: "NAB.ASX",
    stock: "National Australia Bank CFD",
  },
  {
    Symbol: "QBE.ASX",
    stock: "QBE Insurance Group CFD",
  },
  {
    Symbol: "RIO.ASX",
    stock: "Rio Tinto (AUD) CFD",
  },
  {
    Symbol: "SCG.ASX",
    stock: "Scentre Group CFD",
  },
  {
    Symbol: "SUN.ASX",
    stock: "Suncorp Group Ltd CFD",
  },
  {
    Symbol: "TCL.ASX",
    stock: "Transurban Group CFD",
  },
  {
    Symbol: "TLS.ASX",
    stock: "Telstra Corp (AUD) CFD",
  },
  {
    Symbol: "WBC.ASX",
    stock: "Westpac Banking Corp (AUS) CFD",
  },
  {
    Symbol: "WES.ASX",
    stock: "Wesfarmers CFD",
  },
  {
    Symbol: "WOW.ASX",
    stock: "Woolworths (AUD) CFD",
  },
  {
    Symbol: "WPL.ASX",
    stock: "Woodside Petroleum CFD",
  },
];
