// Create and export the cryptocurrency data
export const cryptoData = [
  {
    symbol: "BTCUSDT",
    name: "BITCOIN/TETHERUS",
    price: "98,148.08",
    changePercent: "−0.52%",
    changeValue: "−515.50",
  },
  {
    symbol: "BTCUSD",
    name: "BITCOIN / U.S DOLLAR",
    price: "98,069",
    changePercent: "−0.53%",
    changeValue: "−527.00",
  },
  {
    symbol: "BTCUSD",
    name: "BTC/USD",
    price: "98,065.98",
    changePercent: "−0.54%",
    changeValue: "−528.49",
  },
  {
    symbol: "ETHUSDT",
    name: "ETHEREUM/TETHERUS",
    price: "3,474.45",
    changePercent: "−0.54%",
    changeValue: "−18.73",
  },
  {
    symbol: "ADAUSDT",
    name: "CARDANO / TETHERUS",
    price: "0.9111",
    changePercent: "−2.64%",
    changeValue: "−0.02",
  },
  {
    symbol: "SHIBUSDT",
    name: "SHIB / TETHERUS",
    price: "0.00002292",
    changePercent: "−2.47%",
    changeValue: "−0.00",
  },
  {
    symbol: "MATICUSDT",
    name: "MATIC NETWORK / TETHERUS",
    price: "-",
    changePercent: "-",
    changeValue: "-",
  }, // Placeholder for missing data
  {
    symbol: "SOLUSDT",
    name: "SOL / TETHERUS",
    price: "195.81",
    changePercent: "−0.65%",
    changeValue: "−1.28",
  },
  {
    symbol: "SANDUSDT",
    name: "SAND / TETHERUS",
    price: "0.6081",
    changePercent: "−5.04%",
    changeValue: "−0.03",
  },
  {
    symbol: "ETHUSD",
    name: "ETHEREUM / U.S DOLLAR",
    price: "3,471.7",
    changePercent: "−0.59%",
    changeValue: "−20.60",
  },
];

// Create and export the stock market data
export const stocksData = [
  {
    symbol: "AAPL",
    market: "D",
    companyName: "APPLE INC.",
    price: "258.20",
    changePercent: "+1.15%",
    changeValue: "+2.93",
  },
  {
    symbol: "TSLA",
    market: "D",
    companyName: "TESLA INC.",
    price: "462.28",
    changePercent: "+7.36%",
    changeValue: "+31.68",
  },
  {
    symbol: "QQQ",
    market: "D",
    companyName: "INVESCO QQQ TRUST, SERIES 1",
    price: "529.96",
    changePercent: "+1.36%",
    changeValue: "+7.09",
  },
  {
    symbol: "NVDA",
    market: "D",
    companyName: "NVIDIA CORPORATION",
    price: "140.22",
    changePercent: "+0.39%",
    changeValue: "+0.55",
  },
  {
    symbol: "AMC",
    market: "D",
    companyName: "AMC ENTERTAINMENT HOLDING, INC.",
    price: "4.06",
    changePercent: "−1.46%",
    changeValue: "−0.06",
  },
  {
    symbol: "FB",
    market: "D",
    companyName: "META PLATFORMS, INC.",
    price: "607.75",
    changePercent: "+1.32%",
    changeValue: "+7.90",
  },
  {
    symbol: "AMZN",
    market: "D",
    companyName: "AMAZON.COM, INC.",
    price: "229.05",
    changePercent: "+1.77%",
    changeValue: "+3.99",
  },
  {
    symbol: "BABA",
    market: "D",
    companyName: "ALIBABA GROUP HOLDING LIMITED",
    price: "85.52",
    changePercent: "+0.45%",
    changeValue: "+0.38",
  },
  {
    symbol: "R",
    market: "RELIANCE",
    companyName: "RELIANCE INDS",
    price: "-",
    changePercent: "-",
    changeValue: "-",
  }, // Missing data
  {
    symbol: "AMD",
    market: "D",
    companyName: "ADVANCED MICRO DEVICES, INC.",
    price: "126.29",
    changePercent: "+1.36%",
    changeValue: "+1.69",
  },
];
export const forexData = [
  {
    symbol: "EURUSD",
    name: "EURO F.X/U.S. DOLLAR",
    price: "1.03912",
    changePercent: "−0.13%",
    changeValue: "−0.00133",
  },
  {
    symbol: "GBPUSD",
    name: "BRITISH POUND/U.S. DOLLAR",
    price: "1.25296",
    changePercent: "−0.01%",
    changeValue: "−0.00011",
  },
  {
    symbol: "GBPJPY",
    name: "BRITISH POUND/JAPANESE YEN",
    price: "197.013",
    changePercent: "+0.09%",
    changeValue: "+0.180",
  },
  {
    symbol: "USDJPY",
    name: "U.S. DOLLAR/JAPANESE YEN",
    price: "157.298",
    changePercent: "+0.08%",
    changeValue: "+0.133",
  },
  {
    symbol: "EURUSD",
    name: "EUR/USD",
    price: "1.03966",
    changePercent: "−0.09%",
    changeValue: "−0.00098",
  },
  {
    symbol: "GBPUSD",
    name: "GBP/USD",
    price: "1.25432",
    changePercent: "+0.06%",
    changeValue: "+0.00072",
  },
  {
    symbol: "AUDUSD",
    name: "AUSTRALIAN DOLLAR/U.S DOLLAR",
    price: "0.62326",
    changePercent: "−0.23%",
    changeValue: "−0.00146",
  },
  {
    symbol: "GBPJPY",
    name: "GBP/JPY",
    price: "196.961",
    changePercent: "−0.02%",
    changeValue: "−0.047",
  },
  {
    symbol: "USDCAD",
    name: "U.S. DOLLAR/CANADIAN DOLLAR",
    price: "1.43625",
    changePercent: "−0.05%",
    changeValue: "−0.00067",
  },
  {
    symbol: "USDTRY",
    name: "U.S. DOLLAR/TURKISH NEW LIRA",
    price: "35.17561",
    changePercent: "+0.02%",
    changeValue: "+0.00550",
  },
];
export const indicesData = [
  {
    symbol: "I3G2",
    name: "ING (L) INV-LATIN AMERICA INDICES-PC",
    price: "1,817.8",
    changePercent: "+1.40%",
    changeValue: "+25.2",
  },
  {
    symbol: "IDXFINANCE",
    name: "JAKARTA INDICES",
    price: "1,397.5670",
    changePercent: "−0.33%",
    changeValue: "−4.5710",
  },
  {
    symbol: "IDXENERGY",
    name: "JAKARTA INDICES",
    price: "2,650.5300",
    changePercent: "+0.56%",
    changeValue: "+14.6790",
  },
  {
    symbol: "IDXINFRA",
    name: "JAKARTA INDICES",
    price: "1,459.9980",
    changePercent: "+0.15%",
    changeValue: "+2.1680",
  },
  {
    symbol: "IDXTECHNO",
    name: "JAKARTA INDICES",
    price: "3,977.2730",
    changePercent: "−1.68%",
    changeValue: "−68.0170",
  },
  {
    symbol: "IDXPROPERT",
    name: "JAKARTA INDICES",
    price: "749.1270",
    changePercent: "+0.34%",
    changeValue: "+2.5140",
  },
  {
    symbol: "IDXHEALTH",
    name: "JAKARTA INDICES",
    price: "1,426.9140",
    changePercent: "+2.30%",
    changeValue: "+32.1300",
  },
  {
    symbol: "IDXBASIC",
    name: "JAKARTA INDICES",
    price: "1,237.8700",
    changePercent: "−0.87%",
    changeValue: "−10.8720",
  },
  {
    symbol: "IDXCYCLIC",
    name: "JAKARTA INDICES",
    price: "821.4170",
    changePercent: "−1.19%",
    changeValue: "−9.9310",
  },
  {
    symbol: "IDXTRANS",
    name: "JAKARTA INDICES",
    price: "1,278.0950",
    changePercent: "+0.19%",
    changeValue: "+2.4750",
  },
];
export const commoditiesData = [
  {
    symbol: "CNXCOMMODITIES",
    name: "NIFTY COMMODITIES",
    price: "",
    changePercent: "",
    changeValue: "",
  },
  {
    symbol: "CRB",
    name: "LYXOR COMMODITIES REFINITIV UCITS ETF",
    price: "23.200",
    changePercent: "−0.13%",
    changeValue: "−0.030",
  },
  {
    symbol: "ACOMO",
    name: "AMSTERDAM COMMODITIES",
    price: "",
    changePercent: "",
    changeValue: "",
  },
  {
    symbol: "MRC",
    name: "MINERAL COMMODITIES LTD",
    price: "0.026",
    changePercent: "0.00%",
    changeValue: "0.000",
  },
  {
    symbol: "OD7V",
    name: "WISDOMTREE BROAD COMMODITIES",
    price: "10.524",
    changePercent: "+0.12%",
    changeValue: "+0.012",
  },
  {
    symbol: "P5U7",
    name: "AMUNDI S.F, EUR COMMODITIES",
    price: "26.560",
    changePercent: "+0.18%",
    changeValue: "+0.050",
  },
  {
    symbol: "ACNFF",
    name: "AMSTERDAM COMMODITIES",
    price: "18.45",
    changePercent: "−1.20%",
    changeValue: "−0.23",
  },
  {
    symbol: "CEUMF",
    name: "CENTURY GLOBAL COMMODITIES CORP",
    price: "0.0400",
    changePercent: "−45.95%",
    changeValue: "−0.0340",
  },
  {
    symbol: "DLRYF",
    name: "CARLYLE COMMODITIES CORP",
    price: "",
    changePercent: "",
    changeValue: "",
  },
  {
    symbol: "9GAF",
    name: "WISDOMTREE BROAD COMMODITIES LONGER DATED",
    price: "26.890",
    changePercent: "+0.19%",
    changeValue: "+0.050",
  },
];

export const etfData = [
  {
    symbol: "ETFSP500",
    type: "E",
    name: "ETFSP500",
    price: "251.70",
    changePercent: "−0.20%",
    changeValue: "−0.50",
  },
  {
    symbol: "ACDC",
    type: "D",
    name: "ETFS ACDC ETF UNITS",
    price: "87.37",
    changePercent: "+0.41%",
    changeValue: "+0.36",
  },
  {
    symbol: "GOLD",
    type: "D",
    name: "ETP. ETFS GOLD",
    price: "38.69",
    changePercent: "+0.23%",
    changeValue: "+0.09",
  },
  {
    symbol: "FANG",
    type: "D",
    name: "ETFS FANG ETF UNITS",
    price: "33.54",
    changePercent: "+0.96%",
    changeValue: "+0.32",
  },
  {
    symbol: "HGEN",
    type: "D",
    name: "ETFS HGEN ETF UNITS",
    price: "5.07",
    changePercent: "−0.20%",
    changeValue: "−0.01",
  },
  {
    symbol: "SEMI",
    type: "D",
    name: "ETFS SEMI ETF UNITS",
    price: "17.55",
    changePercent: "+1.62%",
    changeValue: "+0.28",
  },
  {
    symbol: "MAHE",
    type: "E",
    name: "52-WEEK HIGHS ETFS",
    price: "32.00",
    changePercent: "+88.24%",
    changeValue: "+15.00",
  },
  {
    symbol: "EAUSF",
    type: "ETFS METAL SECURITIES AUSTRALIA ETFS PHYSICAL GOLD",
    name: "",
    price: "",
    changePercent: "",
    changeValue: "",
  },
  {
    symbol: "MALE",
    type: "E",
    name: "52-WEEK LOWS ETFS",
    price: "38.00",
    changePercent: "−5.00%",
    changeValue: "−2.00",
  },
  {
    symbol: "JPGLF",
    type: "D",
    name: "JPMORGAN ETFS (IRELAND) ICAV",
    price: "40.71",
    changePercent: "+1.61%",
    changeValue: "+0.65",
  },
];
export const bondData = [
  {
    symbol: "BOND",
    type: "PIMCO ACTIVE BOND EXCHANGE-TRADED FUND EXCHANGE-TRADED FUND",
    name: "",
    price: "",
    changePercent: "",
    changeValue: "",
  },
  {
    symbol: "BOND",
    type: "D",
    name: "SPDR BOND ETF UNITS",
    price: "25.08",
    changePercent: "−0.40%",
    changeValue: "−0.10",
  },
  {
    symbol: "BOND",
    type: "PIMCO ACTIVE BOND EXCHANGE-TRADED FUND",
    name: "",
    price: "",
    changePercent: "",
    changeValue: "",
  },
  {
    symbol: "BONDUSDT",
    type: "BOND / TETHERUS",
    name: "",
    price: "",
    changePercent: "",
    changeValue: "",
  },
  {
    symbol: "BONDBTC",
    type: "BOND / BITCOIN",
    name: "",
    price: "",
    changePercent: "",
    changeValue: "",
  },
  {
    symbol: "BONDUSD",
    type: "BOND / USD",
    name: "",
    price: "",
    changePercent: "",
    changeValue: "",
  },
  {
    symbol: "BONDBUSD",
    type: "BOND / BUSD",
    name: "",
    price: "",
    changePercent: "",
    changeValue: "",
  },
  {
    symbol: "BONDUSD",
    type: "BOND / US DOLLAR",
    name: "",
    price: "",
    changePercent: "",
    changeValue: "",
  },
  {
    symbol: "TLT",
    type: "D",
    name: "ISHARES 20+ YEAR TREASURY BOND ETF",
    price: "87.87",
    changePercent: "+0.42%",
    changeValue: "+0.37",
  },
  {
    symbol: "BONDLYUSDT",
    type: "BONDLY / TETHER",
    name: "",
    price: "",
    changePercent: "",
    changeValue: "",
  },
];
